.nh
.TH "HC" "1" "Jan 2026" "Harness CLI" "Harness CLI Manual"

.SH NAME
hc-registry-migrate - Start a migration based on configuration


.SH SYNOPSIS
\fBhc registry migrate [flags]\fP


.SH DESCRIPTION
Migrate artifacts from a source registry to a Harness Artifact Registry.

.PP
This command reads a YAML configuration file that defines the source and destination
registries, credentials, and artifact mappings.

.PP
Example configuration file (config.yaml):

.PP
version: 1.0.0
  concurrency: 5
  overwrite: false

.PP
source:
    endpoint: https://source-registry.example.com
    type: JFROG                    # Supported: JFROG, NEXUS
    credentials:
      username: source_user
      password: source_password
    insecure: false

.PP
destination:
    endpoint: https://pkg.harness.io
    type: HAR
    credentials:
      username: harness_user
      password: harness_api_key

.PP
mappings:
    - artifactType: DOCKER
      sourceRegistry: docker-repo
      destinationRegistry: harness-docker-repo

.EX
- artifactType: MAVEN
  sourceRegistry: maven-releases
  destinationRegistry: harness-maven

- artifactType: NPM
  sourceRegistry: npm-local
  destinationRegistry: harness-npm

- artifactType: HELM
  sourceRegistry: helm-charts
  destinationRegistry: harness-helm
.EE

.PP
Supported artifact types:
  DOCKER, HELM, HELM_LEGACY, MAVEN, NPM, NUGET, PYTHON, GO, GENERIC, CONDA, COMPOSER

.PP
Environment variables can be used in the config file using ${VAR_NAME} syntax.

.PP
Usage example:
  hc registry migrate -c config.yaml


.SH OPTIONS
\fB--concurrency\fP=1
	Number of concurrent operations (overrides config)

.PP
\fB-c\fP, \fB--config\fP="config.yaml"
	Path to configuration file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for migrate

.PP
\fB--overwrite\fP[=false]
	Allow overwriting artifacts

.PP
\fB--pkg-url\fP=""
	Base URL for the API (overrides config)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--account\fP=""
	Account ID (overrides saved config)

.PP
\fB--api-url\fP=""
	Base URL for the API (overrides saved config)

.PP
\fB--format\fP="table"
	Output format: table or json

.PP
\fB--org\fP=""
	Organisation ID (overrides saved config)

.PP
\fB--project\fP=""
	Project ID (overrides saved config)

.PP
\fB--token\fP=""
	Authentication token (overrides saved config)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose logging to console


.SH SEE ALSO
\fBhc-registry(1)\fP


.SH HISTORY
10-Jan-2026 Auto generated by spf13/cobra
