// SPDX-License-Identifier: Apache-2.0
// Code-gen for Harness multi-service CLI.
// Run by `make generate --service=<svc> --in=<yaml>`.
// Generates:
//
//   internal/api/<svc>/client_gen.go   – via oapi-codegen
//   cmd/<svc>/gen_<resource>_<action>.go – Cobra sub-commands (one per operation)

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
)

var (
	service = flag.String("service", "", "service name (folder under api/)")
	inFile  = flag.String("in", "", "path to openapi.yaml")
	outDir  = flag.String("out", "", "directory for the generated Cobra commands")
	module  = "github.com/harness/harness-cli"
)

func main() {
	flag.Parse()
	if *service == "" || *inFile == "" || *outDir == "" {
		flag.Usage()
		os.Exit(1)
	}

	genClient(*service, *inFile)
	genCommands(*service, *inFile, *outDir)
}

// -------------------------------------------------------------------------
// 1. Generate REST client with oapi-codegen
func genClient(pkg, spec string) {
	targetDir := filepath.Join("internal", "api", pkg)
	must(os.MkdirAll(targetDir, 0o755))

	args := []string{
		"--package", pkg,
		"--generate", "types,client",
		"-response-type-suffix", "Resp",
		"--o", filepath.Join(targetDir, "client_gen.go"),
		spec,
	}

	cmd := exec.Command("oapi-codegen", args...)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	must(cmd.Run())
}

// -------------------------------------------------------------------------
// 2. Generate Cobra commands – one file per operation
//func genCommands(pkg, spec, dir string) {
//	loader := openapi3.NewLoader()
//	doc, err := loader.LoadFromFile(spec)
//	must(err)
//	must(doc.Validate(loader.Context))
//
//	must(os.MkdirAll(filepath.Join(dir, "gen"), 0o755))
//
//	for path, item := range doc.Paths {
//		for method, op := range item.Operations() {
//			res, act := deriveNames(method, path)
//			file := filepath.Join(dir, "gen",
//				fmt.Sprintf("%s_%s_gen.go", res, act))
//
//			// Skip if user already supplied an override WITHOUT "_gen" suffix
//			override := filepath.Join(dir,
//				fmt.Sprintf("%s_%s.go", res, act))
//			if exists(override) {
//				continue
//			}
//
//			writeCmdFile(pkg, res, act, op.OperationID, file)
//		}
//	}
//}

// -------------------------------------------------------------------------
// 2. Generate Cobra commands – one file per operation
func genCommands(pkg, spec, dir string) {
	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromFile(spec)
	must(err)
	must(doc.Validate(loader.Context))

	genDir := filepath.Join(dir, "gen")
	must(os.MkdirAll(genDir, 0o755))

	// NOTE: Paths is no longer a map[string]*PathItem.
	//       Map() returns that map in v0.131.0+
	for path, item := range doc.Paths.Map() {
		if item == nil {
			continue
		}

		for method, op := range item.Operations() {
			res, act := deriveNames(method, path)

			file := filepath.Join(genDir,
				fmt.Sprintf("%s_%s_gen.go", res, act))
			override := filepath.Join(dir,
				fmt.Sprintf("%s_%s.go", res, act))

			if exists(override) {
				// User-supplied implementation beats generated one
				continue
			}
			writeCmdFile(pkg, res, act, method, path, op.OperationID, file)
		}
	}
}

// -------------------------------------------------------------------------
// 3. Helpers
func deriveNames(method, path string) (resource, action string) {
	segments := strings.Split(strings.Trim(path, "/"), "/")
	resource = singular(strings.Split(segments[0], "{")[0])

	switch strings.ToUpper(method) {
	case "GET":
		if strings.Contains(path, "}") {
			action = "get"
		} else {
			action = "list"
		}
	case "POST":
		action = "create"
	case "PUT", "PATCH":
		action = "update"
	case "DELETE":
		action = "delete"
	default:
		action = strings.ToLower(method)
	}
	return
}

func singular(plural string) string {
	if strings.HasSuffix(plural, "ies") {
		return plural[:len(plural)-3] + "y"
	}
	if strings.HasSuffix(plural, "s") {
		return plural[:len(plural)-1]
	}
	return plural
}

var tmpl = template.Must(
	template.New("cmd").
		Funcs(template.FuncMap{
			"title": func(s string) string {
				if len(s) == 0 {
					return s
				}
				return strings.ToUpper(s[:1]) + s[1:]
			},
		}).
		Parse(`// Code generated by cobra-gen; DO NOT EDIT.

package {{ .Pkg }}

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"
	client "{{ .Module }}/internal/api/{{ .Pkg }}"
)

// new{{ .Res | title }}{{ .Act | title }}Cmd wires up:
//   hns {{ .Pkg }} {{ .Res }} {{ .Act }}
func new{{ .Res | title }}{{ .Act | title }}Cmd() *cobra.Command {
	var host string
	cmd := &cobra.Command{
		Use:   "{{ .Res }} {{ .Act }}",
		Short: "{{ .Method }} {{ .Path }}",
		RunE: func(cmd *cobra.Command, args []string) error {
			cli, err := client.NewClient(host, nil)
			if err != nil {
				return err
			}

			// TODO: map flags/args → request parameters
			resp, err := cli.{{ .OpID }}(context.Background())
			if err != nil {
				return err
			}
			fmt.Printf("%+v\n", resp)
			return nil
		},
	}
	cmd.Flags().StringVar(&host, "host", "{{ .DefaultHost }}", "service base URL")
	return cmd
}

func init() {
	ServiceCmd.AddCommand(new{{ .Res | title }}{{ .Act | title }}Cmd())
}
`))

// Helper to upper-case first letter in template
func init() { tmpl = tmpl.Funcs(template.FuncMap{"title": strings.Title}) }

type cmdData struct {
	Pkg, Module        string
	Res, Act           string
	Method, Path, OpID string
	DefaultHost        string
}

func writeCmdFile(pkg, res, act, met, path, opID, filename string) {
	var buf bytes.Buffer
	_ = tmpl.Execute(&buf, cmdData{
		Pkg:         pkg,
		Module:      module,
		Res:         res,
		Act:         act,
		Path:        path, // can be filled if needed
		Method:      met,  // ditto
		OpID:        opID,
		DefaultHost: "http://localhost:8080",
	})

	src, err := format.Source(buf.Bytes())
	must(err)
	must(os.WriteFile(filename, src, 0o644))
}

func exists(path string) bool { _, err := os.Stat(path); return err == nil }

func must(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
