// Package ar_v3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package ar_v3

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiErrorsType.
const (
	APIERROR            ApiErrorsType = "API_ERROR"
	AUTHENTICATIONERROR ApiErrorsType = "AUTHENTICATION_ERROR"
	INVALIDREQUESTERROR ApiErrorsType = "INVALID_REQUEST_ERROR"
	PERMISSIONERROR     ApiErrorsType = "PERMISSION_ERROR"
)

// Defines values for ArtifactScanScanStatus.
const (
	ArtifactScanScanStatusBLOCKED ArtifactScanScanStatus = "BLOCKED"
	ArtifactScanScanStatusWARN    ArtifactScanScanStatus = "WARN"
)

// Defines values for ArtifactScanDetailsScanStatus.
const (
	ArtifactScanDetailsScanStatusBLOCKED ArtifactScanDetailsScanStatus = "BLOCKED"
	ArtifactScanDetailsScanStatusWARN    ArtifactScanDetailsScanStatus = "WARN"
)

// Defines values for ArtifactScanEvaluateRequestStatus.
const (
	FAILED     ArtifactScanEvaluateRequestStatus = "FAILED"
	PENDING    ArtifactScanEvaluateRequestStatus = "PENDING"
	PROCESSING ArtifactScanEvaluateRequestStatus = "PROCESSING"
	SUCCESS    ArtifactScanEvaluateRequestStatus = "SUCCESS"
)

// Defines values for PolicyFailureDetailCategory.
const (
	License    PolicyFailureDetailCategory = "License"
	PackageAge PolicyFailureDetailCategory = "PackageAge"
	Security   PolicyFailureDetailCategory = "Security"
	Unknown    PolicyFailureDetailCategory = "Unknown"
)

// Defines values for RegistryScope.
const (
	RegistryScopeAncestors   RegistryScope = "ancestors"
	RegistryScopeDescendants RegistryScope = "descendants"
	RegistryScopeNone        RegistryScope = "none"
)

// Defines values for SortOrder.
const (
	SortOrderASC  SortOrder = "ASC"
	SortOrderDESC SortOrder = "DESC"
)

// Defines values for GetArtifactScansParamsSortOrder.
const (
	GetArtifactScansParamsSortOrderASC  GetArtifactScansParamsSortOrder = "ASC"
	GetArtifactScansParamsSortOrderDESC GetArtifactScansParamsSortOrder = "DESC"
)

// Defines values for GetArtifactScansParamsScope.
const (
	GetArtifactScansParamsScopeAncestors   GetArtifactScansParamsScope = "ancestors"
	GetArtifactScansParamsScopeDescendants GetArtifactScansParamsScope = "descendants"
	GetArtifactScansParamsScopeNone        GetArtifactScansParamsScope = "none"
)

// ApiErrors defines model for ApiErrors.
type ApiErrors struct {
	// Code For some errors that could be handled programmatically, a short string indicating the [error code](https://docs.stripe.com/error-codes) reported.
	Code *string `json:"code,omitempty"`

	// Message A human-readable message providing more details about the error. These messages can be shown to users.
	Message *string `json:"message,omitempty"`

	// Param If the error is parameter-specific, the parameter related to the error. For example, we can use this to display a message near the correct form field.
	Param *string `json:"param,omitempty"`

	// Type The type of error returned.
	Type ApiErrorsType `json:"type"`
}

// ApiErrorsType The type of error returned.
type ApiErrorsType string

// ArtifactScan defines model for ArtifactScan.
type ArtifactScan struct {
	Id              string  `json:"id"`
	LastEvaluatedAt *string `json:"lastEvaluatedAt,omitempty"`
	LastEvaluatedBy *string `json:"lastEvaluatedBy,omitempty"`

	// PackageName Package name
	PackageName string `json:"packageName"`

	// PackageType Package type. Known values include: DOCKER, MAVEN, PYTHON, GENERIC, HELM, NUGET, NPM, RPM, CARGO, COMPOSER, GO, HUGGINGFACE, CONDA, DART, SWIFT. This field is extensible; clients must handle unknown values.
	PackageType PackageType `json:"packageType"`

	// PolicySets List of opa policy sets.
	PolicySets PolicySets `json:"policySets"`

	// RegistryId Registry name
	RegistryId string `json:"registryId"`

	// RegistryName Registry name
	RegistryName string `json:"registryName"`

	// ScanStatus Scan status
	ScanStatus ArtifactScanScanStatus `json:"scanStatus"`

	// Version Version
	Version string `json:"version"`

	// VersionId Version
	VersionId *string `json:"versionId,omitempty"`
}

// ArtifactScanScanStatus Scan status
type ArtifactScanScanStatus string

// ArtifactScanDetails Artifact scans details
type ArtifactScanDetails struct {
	CreatedAt *string `json:"createdAt,omitempty"`

	// FixVersionDetails Fix version Details
	FixVersionDetails *FixVersionDetails `json:"fixVersionDetails,omitempty"`

	// Id Unique identifier for this artifact scan details
	Id              openapi_types.UUID `json:"id"`
	LastEvaluatedAt *string            `json:"lastEvaluatedAt,omitempty"`

	// PackageName Package name
	PackageName string `json:"packageName"`

	// PackageType Package type. Known values include: DOCKER, MAVEN, PYTHON, GENERIC, HELM, NUGET, NPM, RPM, CARGO, COMPOSER, GO, HUGGINGFACE, CONDA, DART, SWIFT. This field is extensible; clients must handle unknown values.
	PackageType          PackageType           `json:"packageType"`
	PolicyFailureDetails []PolicyFailureDetail `json:"policyFailureDetails"`
	PolicySetName        *string               `json:"policySetName,omitempty"`
	PolicySetRef         *string               `json:"policySetRef,omitempty"`

	// RegistryId Registry ID
	RegistryId *openapi_types.UUID `json:"registryId,omitempty"`

	// RegistryName Registry name
	RegistryName string `json:"registryName"`

	// ScanStatus Scan status
	ScanStatus ArtifactScanDetailsScanStatus `json:"scanStatus"`

	// Version Version
	Version string `json:"version"`

	// VersionId Version
	VersionId *openapi_types.UUID `json:"versionId,omitempty"`
}

// ArtifactScanDetailsScanStatus Scan status
type ArtifactScanDetailsScanStatus string

// ArtifactScanEvaluateRequest Input for re-evaluate artifact scan.
// Exactly one of scanId or versionId must be provided.
type ArtifactScanEvaluateRequest struct {
	// ScanId Scan identifier
	ScanId *string `json:"scanId,omitempty"`

	// VersionId Artifact version identifier
	VersionId *string `json:"versionId,omitempty"`
}

// ArtifactScanEvaluateRequestStatus Status of the Artifact Scan Evaluate Request
type ArtifactScanEvaluateRequestStatus string

// FixVersionDetails Fix version Details
type FixVersionDetails struct {
	// CurrentVersion The current version
	CurrentVersion string `json:"currentVersion"`

	// FixVersion The fix version
	FixVersion *string `json:"fixVersion,omitempty"`

	// FixVersionAvailable Fix version available or not
	FixVersionAvailable bool `json:"fixVersionAvailable"`
}

// LicensePolicyFailureDetailConfig License-specific failure detail payload.
type LicensePolicyFailureDetailConfig struct {
	// AllowedLicenses Allowed license list.
	AllowedLicenses []string `json:"allowedLicenses"`

	// BlockedLicense Blocked license.
	BlockedLicense string `json:"blockedLicense"`
}

// PackageAgeViolationPolicyFailureDetailConfig Package age violation failure detail payload.
type PackageAgeViolationPolicyFailureDetailConfig struct {
	// PackageAgeThreshold Package age threshold.
	PackageAgeThreshold string `json:"packageAgeThreshold"`

	// PublishedOn Package publish date.
	PublishedOn string `json:"publishedOn"`
}

// PackageType Package type. Known values include: DOCKER, MAVEN, PYTHON, GENERIC, HELM, NUGET, NPM, RPM, CARGO, COMPOSER, GO, HUGGINGFACE, CONDA, DART, SWIFT. This field is extensible; clients must handle unknown values.
type PackageType = string

// PolicyFailureDetail Policy failure detail entry.
type PolicyFailureDetail struct {
	// Category Policy failure detail category.
	Category PolicyFailureDetailCategory `json:"category"`

	// PolicyName Policy name.
	PolicyName string `json:"policyName"`

	// PolicyRef Policy Ref.
	PolicyRef string `json:"policyRef"`
	union     json.RawMessage
}

// PolicyFailureDetailCategory Policy failure detail category.
type PolicyFailureDetailCategory string

// ScanMeta Metadata about the list artifact scans
type ScanMeta struct {
	// BlockedCount Count of active blocked artifacts
	BlockedCount *int64 `json:"blockedCount,omitempty"`

	// TotalCount Count of total artifact violations
	TotalCount *int64 `json:"totalCount,omitempty"`

	// WarnCount Count of active Warn artifacts
	WarnCount *int64 `json:"warnCount,omitempty"`
}

// SecurityPolicyFailureDetailConfig Security-specific failure detail payload.
type SecurityPolicyFailureDetailConfig struct {
	// Vulnerabilities List of security violations.
	Vulnerabilities []SecurityPolicyFailureVulnerability `json:"vulnerabilities"`
}

// SecurityPolicyFailureVulnerability Security violation entry.
type SecurityPolicyFailureVulnerability struct {
	// CveId CVE identifier.
	CveId string `json:"cveId"`

	// CvssScore CVSS score.
	CvssScore float64 `json:"cvssScore"`

	// CvssThreshold CVSS threshold.
	CvssThreshold float64 `json:"cvssThreshold"`
}

// V3Error An error response from the Stripe API
type V3Error struct {
	Error ApiErrors `json:"error"`
}

// PolicySets List of opa policy sets.
type PolicySets = []struct {
	// PolicySetName Policy Set name
	PolicySetName string `json:"policySetName"`

	// PolicySetRef Unique reference for the opa policy set. Example: `my-policy` or `account.my-policy`
	PolicySetRef string `json:"policySetRef"`
}

// AccountIdentifier defines model for AccountIdentifier.
type AccountIdentifier = string

// OrgIdentifier defines model for OrgIdentifier.
type OrgIdentifier = string

// PackageTypeListParam defines model for PackageTypeListParam.
type PackageTypeListParam = []string

// PageNumber defines model for PageNumber.
type PageNumber = int64

// PageSize defines model for PageSize.
type PageSize = int64

// PolicySetRefParam defines model for PolicySetRefParam.
type PolicySetRefParam = string

// ProjectIdentifier defines model for ProjectIdentifier.
type ProjectIdentifier = string

// RegistryIdListParam defines model for RegistryIdListParam.
type RegistryIdListParam = []openapi_types.UUID

// RegistryScope defines model for RegistryScope.
type RegistryScope string

// ScanIDParam defines model for ScanIDParam.
type ScanIDParam = string

// ScanIDQueryParam defines model for ScanIDQueryParam.
type ScanIDQueryParam = string

// ScanStatusParam defines model for ScanStatusParam.
type ScanStatusParam = string

// SearchTerm defines model for SearchTerm.
type SearchTerm = string

// SortField defines model for SortField.
type SortField = string

// SortOrder defines model for SortOrder.
type SortOrder string

// ArtifactScanDetailsResponse defines model for ArtifactScanDetailsResponse.
type ArtifactScanDetailsResponse struct {
	// Data Artifact scans details
	Data *ArtifactScanDetails `json:"data,omitempty"`
}

// ArtifactScanEvaluateRequestAccepted defines model for ArtifactScanEvaluateRequestAccepted.
type ArtifactScanEvaluateRequestAccepted struct {
	// Data Status of the Artifact Scan Evaluate Request
	Data *ArtifactScanEvaluateRequestStatus `json:"data,omitempty"`
}

// ListArtifactScanResponse defines model for ListArtifactScanResponse.
type ListArtifactScanResponse struct {
	// Data A list of artifact scans
	Data []ArtifactScan `json:"data"`

	// ItemCount The total number of items
	ItemCount int64 `json:"itemCount"`

	// Meta Metadata about the list artifact scans
	Meta ScanMeta `json:"meta"`

	// PageCount The total number of pages
	PageCount int64 `json:"pageCount"`

	// PageIndex The current page
	PageIndex int64 `json:"pageIndex"`

	// PageSize The number of items per page
	PageSize int `json:"pageSize"`
}

// GetArtifactScansParams defines parameters for GetArtifactScans.
type GetArtifactScansParams struct {
	// AccountIdentifier Unique identifier for the Harness account.
	AccountIdentifier AccountIdentifier `form:"account_identifier" json:"account_identifier"`

	// OrgIdentifier Unique identifier for the organization within the account.
	//
	// Example: `default` or `engineering_org`
	OrgIdentifier *OrgIdentifier `form:"org_identifier,omitempty" json:"org_identifier,omitempty"`

	// ProjectIdentifier Unique identifier for the project within the organization.
	//
	// Example: `my_project` or `frontend_services`
	ProjectIdentifier *ProjectIdentifier `form:"project_identifier,omitempty" json:"project_identifier,omitempty"`

	// PackageType Registry Package Type
	PackageType *PackageTypeListParam `form:"package_type,omitempty" json:"package_type,omitempty"`

	// RegistryId Unique id for the registry.
	// Note: This parameter should have one id if package query param is provided
	RegistryId *RegistryIdListParam `form:"registry_id,omitempty" json:"registry_id,omitempty"`

	// PolicySetRef Unique reference for the opa policy set. Example: `my-policy` or `account.my-policy
	PolicySetRef *PolicySetRefParam `form:"policy_set_ref,omitempty" json:"policy_set_ref,omitempty"`

	// ScanId Scan Identifier
	ScanId *ScanIDQueryParam `form:"scan_id,omitempty" json:"scan_id,omitempty"`

	// ScanStatus Scan status of the artifact after opa policy evaluation. Note: It can only be BLOCKED or WARN
	ScanStatus *ScanStatusParam `form:"scan_status,omitempty" json:"scan_status,omitempty"`

	// Page The page number for pagination (0-indexed).
	//
	// Used to navigate through large result sets. Combined with `size` parameter
	// to control which subset of results to return.
	//
	// Example: `page=0` returns the first page, `page=1` returns the second page
	Page *PageNumber `form:"page,omitempty" json:"page,omitempty"`

	// Size The number of items to return per page.
	//
	// Controls the page size for paginated results.
	//
	// Example: `size=50` returns up to 50 items per page
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`

	// SortOrder The sort order for the results.
	//
	// Determines whether results are sorted in ascending or descending order.
	// Must be used in combination with `sort_field` parameter.
	//
	// Allowed values: `ASC` (ascending), `DESC` (descending)
	SortOrder *GetArtifactScansParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`

	// SortField The field by which to sort the results.
	//
	// Specifies which field should be used for sorting. Available fields depend
	// on the endpoint and the type of data being returned.
	//
	// Common examples: `name`, `createdAt`, `updatedAt`
	SortField *SortField `form:"sort_field,omitempty" json:"sort_field,omitempty"`

	// SearchTerm Search term for filtering results.
	//
	// Example: `search_term=prod` might match keys like "production", "prod-env", etc.
	SearchTerm *SearchTerm `form:"search_term,omitempty" json:"search_term,omitempty"`

	// Scope **Scope of registries to list**
	// * **none** – current space only (default)   * **ancestors** – current space **plus** all parent spaces   * **descendants** – current space **plus** all child spaces
	// If omitted, `none` is assumed.
	Scope *GetArtifactScansParamsScope `form:"scope,omitempty" json:"scope,omitempty"`
}

// GetArtifactScansParamsSortOrder defines parameters for GetArtifactScans.
type GetArtifactScansParamsSortOrder string

// GetArtifactScansParamsScope defines parameters for GetArtifactScans.
type GetArtifactScansParamsScope string

// EvaluateArtifactScanParams defines parameters for EvaluateArtifactScan.
type EvaluateArtifactScanParams struct {
	// AccountIdentifier Unique identifier for the Harness account.
	AccountIdentifier AccountIdentifier `form:"account_identifier" json:"account_identifier"`
}

// GetArtifactScanDetailsParams defines parameters for GetArtifactScanDetails.
type GetArtifactScanDetailsParams struct {
	// AccountIdentifier Unique identifier for the Harness account.
	AccountIdentifier AccountIdentifier `form:"account_identifier" json:"account_identifier"`

	// PolicySetRef Unique reference for the opa policy set. Example: `my-policy` or `account.my-policy
	PolicySetRef *PolicySetRefParam `form:"policy_set_ref,omitempty" json:"policy_set_ref,omitempty"`
}

// EvaluateArtifactScanJSONRequestBody defines body for EvaluateArtifactScan for application/json ContentType.
type EvaluateArtifactScanJSONRequestBody = ArtifactScanEvaluateRequest

// AsSecurityPolicyFailureDetailConfig returns the union data inside the PolicyFailureDetail as a SecurityPolicyFailureDetailConfig
func (t PolicyFailureDetail) AsSecurityPolicyFailureDetailConfig() (SecurityPolicyFailureDetailConfig, error) {
	var body SecurityPolicyFailureDetailConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSecurityPolicyFailureDetailConfig overwrites any union data inside the PolicyFailureDetail as the provided SecurityPolicyFailureDetailConfig
func (t *PolicyFailureDetail) FromSecurityPolicyFailureDetailConfig(v SecurityPolicyFailureDetailConfig) error {
	t.Category = "SecurityPolicyFailureDetailConfig"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSecurityPolicyFailureDetailConfig performs a merge with any union data inside the PolicyFailureDetail, using the provided SecurityPolicyFailureDetailConfig
func (t *PolicyFailureDetail) MergeSecurityPolicyFailureDetailConfig(v SecurityPolicyFailureDetailConfig) error {
	t.Category = "SecurityPolicyFailureDetailConfig"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLicensePolicyFailureDetailConfig returns the union data inside the PolicyFailureDetail as a LicensePolicyFailureDetailConfig
func (t PolicyFailureDetail) AsLicensePolicyFailureDetailConfig() (LicensePolicyFailureDetailConfig, error) {
	var body LicensePolicyFailureDetailConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLicensePolicyFailureDetailConfig overwrites any union data inside the PolicyFailureDetail as the provided LicensePolicyFailureDetailConfig
func (t *PolicyFailureDetail) FromLicensePolicyFailureDetailConfig(v LicensePolicyFailureDetailConfig) error {
	t.Category = "LicensePolicyFailureDetailConfig"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLicensePolicyFailureDetailConfig performs a merge with any union data inside the PolicyFailureDetail, using the provided LicensePolicyFailureDetailConfig
func (t *PolicyFailureDetail) MergeLicensePolicyFailureDetailConfig(v LicensePolicyFailureDetailConfig) error {
	t.Category = "LicensePolicyFailureDetailConfig"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPackageAgeViolationPolicyFailureDetailConfig returns the union data inside the PolicyFailureDetail as a PackageAgeViolationPolicyFailureDetailConfig
func (t PolicyFailureDetail) AsPackageAgeViolationPolicyFailureDetailConfig() (PackageAgeViolationPolicyFailureDetailConfig, error) {
	var body PackageAgeViolationPolicyFailureDetailConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPackageAgeViolationPolicyFailureDetailConfig overwrites any union data inside the PolicyFailureDetail as the provided PackageAgeViolationPolicyFailureDetailConfig
func (t *PolicyFailureDetail) FromPackageAgeViolationPolicyFailureDetailConfig(v PackageAgeViolationPolicyFailureDetailConfig) error {
	t.Category = "PackageAgeViolationPolicyFailureDetailConfig"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePackageAgeViolationPolicyFailureDetailConfig performs a merge with any union data inside the PolicyFailureDetail, using the provided PackageAgeViolationPolicyFailureDetailConfig
func (t *PolicyFailureDetail) MergePackageAgeViolationPolicyFailureDetailConfig(v PackageAgeViolationPolicyFailureDetailConfig) error {
	t.Category = "PackageAgeViolationPolicyFailureDetailConfig"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PolicyFailureDetail) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"category"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t PolicyFailureDetail) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "LicensePolicyFailureDetailConfig":
		return t.AsLicensePolicyFailureDetailConfig()
	case "PackageAgeViolationPolicyFailureDetailConfig":
		return t.AsPackageAgeViolationPolicyFailureDetailConfig()
	case "SecurityPolicyFailureDetailConfig":
		return t.AsSecurityPolicyFailureDetailConfig()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t PolicyFailureDetail) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["category"], err = json.Marshal(t.Category)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'category': %w", err)
	}

	object["policyName"], err = json.Marshal(t.PolicyName)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'policyName': %w", err)
	}

	object["policyRef"], err = json.Marshal(t.PolicyRef)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'policyRef': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *PolicyFailureDetail) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["category"]; found {
		err = json.Unmarshal(raw, &t.Category)
		if err != nil {
			return fmt.Errorf("error reading 'category': %w", err)
		}
	}

	if raw, found := object["policyName"]; found {
		err = json.Unmarshal(raw, &t.PolicyName)
		if err != nil {
			return fmt.Errorf("error reading 'policyName': %w", err)
		}
	}

	if raw, found := object["policyRef"]; found {
		err = json.Unmarshal(raw, &t.PolicyRef)
		if err != nil {
			return fmt.Errorf("error reading 'policyRef': %w", err)
		}
	}

	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetArtifactScans request
	GetArtifactScans(ctx context.Context, params *GetArtifactScansParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EvaluateArtifactScanWithBody request with any body
	EvaluateArtifactScanWithBody(ctx context.Context, params *EvaluateArtifactScanParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EvaluateArtifactScan(ctx context.Context, params *EvaluateArtifactScanParams, body EvaluateArtifactScanJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetArtifactScanDetails request
	GetArtifactScanDetails(ctx context.Context, scanId ScanIDParam, params *GetArtifactScanDetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetArtifactScans(ctx context.Context, params *GetArtifactScansParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArtifactScansRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EvaluateArtifactScanWithBody(ctx context.Context, params *EvaluateArtifactScanParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEvaluateArtifactScanRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EvaluateArtifactScan(ctx context.Context, params *EvaluateArtifactScanParams, body EvaluateArtifactScanJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEvaluateArtifactScanRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetArtifactScanDetails(ctx context.Context, scanId ScanIDParam, params *GetArtifactScanDetailsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArtifactScanDetailsRequest(c.Server, scanId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetArtifactScansRequest generates requests for GetArtifactScans
func NewGetArtifactScansRequest(server string, params *GetArtifactScansParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/scans")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "account_identifier", runtime.ParamLocationQuery, params.AccountIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.OrgIdentifier != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "org_identifier", runtime.ParamLocationQuery, *params.OrgIdentifier); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProjectIdentifier != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project_identifier", runtime.ParamLocationQuery, *params.ProjectIdentifier); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PackageType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "package_type", runtime.ParamLocationQuery, *params.PackageType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RegistryId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", false, "registry_id", runtime.ParamLocationQuery, *params.RegistryId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PolicySetRef != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "policy_set_ref", runtime.ParamLocationQuery, *params.PolicySetRef); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ScanId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "scan_id", runtime.ParamLocationQuery, *params.ScanId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ScanStatus != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "scan_status", runtime.ParamLocationQuery, *params.ScanStatus); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Size != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "size", runtime.ParamLocationQuery, *params.Size); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortOrder != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_order", runtime.ParamLocationQuery, *params.SortOrder); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortField != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_field", runtime.ParamLocationQuery, *params.SortField); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SearchTerm != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search_term", runtime.ParamLocationQuery, *params.SearchTerm); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Scope != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "scope", runtime.ParamLocationQuery, *params.Scope); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEvaluateArtifactScanRequest calls the generic EvaluateArtifactScan builder with application/json body
func NewEvaluateArtifactScanRequest(server string, params *EvaluateArtifactScanParams, body EvaluateArtifactScanJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEvaluateArtifactScanRequestWithBody(server, params, "application/json", bodyReader)
}

// NewEvaluateArtifactScanRequestWithBody generates requests for EvaluateArtifactScan with any type of body
func NewEvaluateArtifactScanRequestWithBody(server string, params *EvaluateArtifactScanParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/scans/evaluate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "account_identifier", runtime.ParamLocationQuery, params.AccountIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetArtifactScanDetailsRequest generates requests for GetArtifactScanDetails
func NewGetArtifactScanDetailsRequest(server string, scanId ScanIDParam, params *GetArtifactScanDetailsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "scan_id", runtime.ParamLocationPath, scanId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/scans/%s/details", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "account_identifier", runtime.ParamLocationQuery, params.AccountIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.PolicySetRef != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "policy_set_ref", runtime.ParamLocationQuery, *params.PolicySetRef); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetArtifactScansWithResponse request
	GetArtifactScansWithResponse(ctx context.Context, params *GetArtifactScansParams, reqEditors ...RequestEditorFn) (*GetArtifactScansResp, error)

	// EvaluateArtifactScanWithBodyWithResponse request with any body
	EvaluateArtifactScanWithBodyWithResponse(ctx context.Context, params *EvaluateArtifactScanParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EvaluateArtifactScanResp, error)

	EvaluateArtifactScanWithResponse(ctx context.Context, params *EvaluateArtifactScanParams, body EvaluateArtifactScanJSONRequestBody, reqEditors ...RequestEditorFn) (*EvaluateArtifactScanResp, error)

	// GetArtifactScanDetailsWithResponse request
	GetArtifactScanDetailsWithResponse(ctx context.Context, scanId ScanIDParam, params *GetArtifactScanDetailsParams, reqEditors ...RequestEditorFn) (*GetArtifactScanDetailsResp, error)
}

type GetArtifactScansResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListArtifactScanResponse
	JSONDefault  *V3Error
}

// Status returns HTTPResponse.Status
func (r GetArtifactScansResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArtifactScansResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EvaluateArtifactScanResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ArtifactScanEvaluateRequestAccepted
	JSONDefault  *V3Error
}

// Status returns HTTPResponse.Status
func (r EvaluateArtifactScanResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EvaluateArtifactScanResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetArtifactScanDetailsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ArtifactScanDetailsResponse
	JSONDefault  *V3Error
}

// Status returns HTTPResponse.Status
func (r GetArtifactScanDetailsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArtifactScanDetailsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetArtifactScansWithResponse request returning *GetArtifactScansResp
func (c *ClientWithResponses) GetArtifactScansWithResponse(ctx context.Context, params *GetArtifactScansParams, reqEditors ...RequestEditorFn) (*GetArtifactScansResp, error) {
	rsp, err := c.GetArtifactScans(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArtifactScansResp(rsp)
}

// EvaluateArtifactScanWithBodyWithResponse request with arbitrary body returning *EvaluateArtifactScanResp
func (c *ClientWithResponses) EvaluateArtifactScanWithBodyWithResponse(ctx context.Context, params *EvaluateArtifactScanParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EvaluateArtifactScanResp, error) {
	rsp, err := c.EvaluateArtifactScanWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEvaluateArtifactScanResp(rsp)
}

func (c *ClientWithResponses) EvaluateArtifactScanWithResponse(ctx context.Context, params *EvaluateArtifactScanParams, body EvaluateArtifactScanJSONRequestBody, reqEditors ...RequestEditorFn) (*EvaluateArtifactScanResp, error) {
	rsp, err := c.EvaluateArtifactScan(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEvaluateArtifactScanResp(rsp)
}

// GetArtifactScanDetailsWithResponse request returning *GetArtifactScanDetailsResp
func (c *ClientWithResponses) GetArtifactScanDetailsWithResponse(ctx context.Context, scanId ScanIDParam, params *GetArtifactScanDetailsParams, reqEditors ...RequestEditorFn) (*GetArtifactScanDetailsResp, error) {
	rsp, err := c.GetArtifactScanDetails(ctx, scanId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArtifactScanDetailsResp(rsp)
}

// ParseGetArtifactScansResp parses an HTTP response from a GetArtifactScansWithResponse call
func ParseGetArtifactScansResp(rsp *http.Response) (*GetArtifactScansResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArtifactScansResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListArtifactScanResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest V3Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseEvaluateArtifactScanResp parses an HTTP response from a EvaluateArtifactScanWithResponse call
func ParseEvaluateArtifactScanResp(rsp *http.Response) (*EvaluateArtifactScanResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EvaluateArtifactScanResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ArtifactScanEvaluateRequestAccepted
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest V3Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetArtifactScanDetailsResp parses an HTTP response from a GetArtifactScanDetailsWithResponse call
func ParseGetArtifactScanDetailsResp(rsp *http.Response) (*GetArtifactScanDetailsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArtifactScanDetailsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ArtifactScanDetailsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest V3Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
