gitops:
  name: gitops-application-demo-20
  projectIdentifier: communityeng
  orgIdentifier: default
  type: application
  application:
    metadata:
      namespace: default
      clusterName: demoasd
      labels:
        harness.io/serviceRef: service
        harness.io/envRef: env
    spec:
      source:
        repoURL: https://github.com/harness-community/harnesscd-example-apps
        path: guestbook
        targetRevision: master
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  agentIdentifier: AGENT_NAME
  clusterIdentifier: demoasd
  repoIdentifier: harnessexample