version: 1.0.0
concurrency: 5
overwrite: false
source:
  endpoint: ${SRC_ENDPOINT}
  type: ${SRC_TYPE}
  credentials:
    username: ${SRC_USER}
    password: ${SRC_PASS}
  insecure: true
destination:
  endpoint: ${DST_ENDPOINT}
  type: HAR
  credentials:
    username: ${DST_USER}
    password: ${DST_PASS}
mappings:
  - artifactType: HELM_LEGACY
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: HELM_HTTP
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: MAVEN
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: PYTHON
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: HELM
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: MAVEN
    sourceRegistry: src
    excludePatterns:
      - com/*
      - foo/*
    destinationRegistry: dst
  - artifactType: GENERIC
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: NUGET
    sourceRegistry: src
    dateFilter:
      match: ANY
      createdAfter: 2023-01-01T00:00:00.000Z
      downloadedAfter: 2026-06-01T00:00:00.000Z
    destinationRegistry: dst
  - artifactType: NPM
    sourceRegistry: src
    dateFilter:
      match: ALL
      createdAfter: 2023-01-01T00:00:00.000Z
      downloadedAfter: 2026-06-01T00:00:00.000Z
    destinationRegistry: npm
  - artifactType: GO
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: CONDA
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: COMPOSER
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: DART
    sourceRegistry: src
    destinationRegistry: dst
    includePatterns:
      - packages/sample_dart_pkg/**
  - artifactType: SWIFT
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: PUPPET
    sourceRegistry: src
    destinationRegistry: dst