package jfrog

import (
	"context"
	"fmt"
	"github.com/goharbor/harbor/src/lib/log"
	"harness/clients/ar"
	"harness/module/ar/migrate/adapter"
	"harness/module/ar/migrate/types"
)

// factory section
type factory struct {
}

func init() {
	adapterType := types.HAR
	if err := adapter.RegisterFactory(adapterType, new(factory)); err != nil {
		return
	}
}

// Create an adapter section
func (f factory) Create(ctx context.Context, config types.RegistryConfig) (adapter.Adapter, error) {
	return newAdapter(config)
}

func newAdapter(config types.RegistryConfig) (adapter.Adapter, error) {
	return newClient(&config), nil
}

// ListArtifacts lists all artifacts from a specified registry
func (a *client) ListArtifacts(registry string, artifactType types.ArtifactType) ([]types.Artifact, error) {
	// Placeholder implementation
	return []types.Artifact{
		{
			Name:   "sample-image",
			Tag:    "latest",
			Type:   "docker",
			Size:   1024 * 1024 * 20,
			Digest: "sha256:abcdef1234567890",
		},
	}, nil
}

// PrepareForPush prepares for first push
func (a *client) PrepareForPush(registryID string, packageType string) (string, error) {
	_, err2 := a.apiClient.GetRegistry(registryID)
	if err2 == nil {
		log.Infof("Registry %s already created", registryID)
		return registryID, nil
	}

	registry, err := a.apiClient.CreateRegistry(ar.RegistryRequest{
		Identifier:  registryID,
		PackageType: packageType,
		Description: "Generated by harness cli tool",
	})
	if err != nil {
		return "", fmt.Errorf("failed to create registry: %s, %w", registryID, err)
	}
	return registry.Data.Identifier, nil
}

// PullArtifact pulls an artifact
func (a *client) PullArtifact(registry string, artifact types.Artifact) ([]byte, error) {
	return []byte("artifact data"), nil
}

// PushArtifact pushes an artifact
func (a *client) PushArtifact(registry string, artifact types.Artifact, data []byte) error {
	// Implementation for pushing an artifact to JFrog
	// This would make an API call to the JFrog endpoint

	// Placeholder implementation
	return nil
}
