on:
  release:
    types: [created]
  push:
    branches: [ "feat/install-cli" ]
  pull_request:
    branches: [ "feat/install-cli" ]
permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.34
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19
          project_path: "."
          binary_name: "harness"
          ldflags: ${{ format('-X "main.Version={0}"', github.ref_name) }}

      - name: Move binary to the release directory
        run: |
          mkdir release
          mv harness release/
          cp ./install_scripts/${{ matrix.goos }}/* release/
        working-directory: ${{ github.workspace }}

      - name: Bundle everything inside release directory
        run: |
          tar czvf release.tar.gz release/
        working-directory: ${{ github.workspace }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: release.tar.gz