// Package ar_pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package ar_pkg

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// UploadCargoPackageMultipartBody defines parameters for UploadCargoPackage.
type UploadCargoPackageMultipartBody struct {
	// File Package .cargo file to upload
	File *openapi_types.File `json:"file,omitempty"`
}

// DownloadGenericPackageParams defines parameters for DownloadGenericPackage.
type DownloadGenericPackageParams struct {
	Filename string `form:"filename" json:"filename"`
}

// UploadGenericPackageMultipartBody defines parameters for UploadGenericPackage.
type UploadGenericPackageMultipartBody struct {
	// Description Human-readable description of the package/version
	Description *string `json:"description,omitempty"`

	// File Package file to upload
	File openapi_types.File `json:"file"`

	// Filename Original filename (mirrors form field `filename`)
	Filename string `json:"filename"`
}

// UploadGoPackageMultipartBody defines parameters for UploadGoPackage.
type UploadGoPackageMultipartBody struct {
	// Info Package .info file to upload
	Info openapi_types.File `json:"info"`

	// Mod Package .mod file to upload
	Mod openapi_types.File `json:"mod"`

	// Zip Package .zip file to upload
	Zip openapi_types.File `json:"zip"`
}

// UploadNugetPackageMultipartBody defines parameters for UploadNugetPackage.
type UploadNugetPackageMultipartBody struct {
	// File Package .nupkg file to upload
	File *openapi_types.File `json:"file,omitempty"`
}

// UploadDartPackageMultipartBody defines parameters for UploadDartPackage.
type UploadDartPackageMultipartBody struct {
	// File Package binary file to upload
	File openapi_types.File `json:"file"`
}

// UploadPythonPackageMultipartBody defines parameters for UploadPythonPackage.
type UploadPythonPackageMultipartBody struct {
	// File Package .whl or .tar.gz file to upload
	File *openapi_types.File `json:"file,omitempty"`
}

// UploadRpmPackageMultipartBody defines parameters for UploadRpmPackage.
type UploadRpmPackageMultipartBody struct {
	// File Package .rpm file to upload
	File *openapi_types.File `json:"file,omitempty"`
}

// UploadCargoPackageMultipartRequestBody defines body for UploadCargoPackage for multipart/form-data ContentType.
type UploadCargoPackageMultipartRequestBody UploadCargoPackageMultipartBody

// UploadGenericPackageMultipartRequestBody defines body for UploadGenericPackage for multipart/form-data ContentType.
type UploadGenericPackageMultipartRequestBody UploadGenericPackageMultipartBody

// UploadGoPackageMultipartRequestBody defines body for UploadGoPackage for multipart/form-data ContentType.
type UploadGoPackageMultipartRequestBody UploadGoPackageMultipartBody

// UploadNugetPackageMultipartRequestBody defines body for UploadNugetPackage for multipart/form-data ContentType.
type UploadNugetPackageMultipartRequestBody UploadNugetPackageMultipartBody

// UploadDartPackageMultipartRequestBody defines body for UploadDartPackage for multipart/form-data ContentType.
type UploadDartPackageMultipartRequestBody UploadDartPackageMultipartBody

// UploadPythonPackageMultipartRequestBody defines body for UploadPythonPackage for multipart/form-data ContentType.
type UploadPythonPackageMultipartRequestBody UploadPythonPackageMultipartBody

// UploadRpmPackageMultipartRequestBody defines body for UploadRpmPackage for multipart/form-data ContentType.
type UploadRpmPackageMultipartRequestBody UploadRpmPackageMultipartBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// UploadCargoPackageWithBody request with any body
	UploadCargoPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadComposerPackageWithBody request with any body
	UploadComposerPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadCondaPackageWithBody request with any body
	UploadCondaPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteGenericFileFromPath request
	DeleteGenericFileFromPath(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadGenericFileFromPath request
	DownloadGenericFileFromPath(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeadGenericFileAtPath request
	HeadGenericFileAtPath(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadGenericFileToPathWithBody request with any body
	UploadGenericFileToPathWithBody(ctx context.Context, accountId string, registry string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadGenericPackage request
	DownloadGenericPackage(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadGenericPackageWithBody request with any body
	UploadGenericPackageWithBody(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadGoPackageWithBody request with any body
	UploadGoPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadMavenMetadataXml request
	DownloadMavenMetadataXml(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadMavenMetadataXmlWithBody request with any body
	UploadMavenMetadataXmlWithBody(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadMavenPackageWithBody request with any body
	UploadMavenPackageWithBody(ctx context.Context, accountId string, registry string, groupId string, artifactId string, version string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadNPMPackageMetadata request
	DownloadNPMPackageMetadata(ctx context.Context, accountId string, registry string, pPackage string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadNPMPackageWithBody request with any body
	UploadNPMPackageWithBody(ctx context.Context, accountId string, registry string, pPackage string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadNugetPackageWithBody request with any body
	UploadNugetPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadDartPackageWithBody request with any body
	UploadDartPackageWithBody(ctx context.Context, accountId string, registry string, uploadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadPythonPackageWithBody request with any body
	UploadPythonPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadRpmPackageWithBody request with any body
	UploadRpmPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) UploadCargoPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadCargoPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadComposerPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadComposerPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadCondaPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadCondaPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteGenericFileFromPath(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteGenericFileFromPathRequest(c.Server, accountId, registry, filepath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadGenericFileFromPath(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadGenericFileFromPathRequest(c.Server, accountId, registry, filepath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeadGenericFileAtPath(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeadGenericFileAtPathRequest(c.Server, accountId, registry, filepath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadGenericFileToPathWithBody(ctx context.Context, accountId string, registry string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadGenericFileToPathRequestWithBody(c.Server, accountId, registry, filepath, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadGenericPackage(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadGenericPackageRequest(c.Server, accountId, registry, pPackage, version, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadGenericPackageWithBody(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadGenericPackageRequestWithBody(c.Server, accountId, registry, pPackage, version, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadGoPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadGoPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadMavenMetadataXml(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadMavenMetadataXmlRequest(c.Server, accountId, registry, groupId, artifactId, file)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadMavenMetadataXmlWithBody(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadMavenMetadataXmlRequestWithBody(c.Server, accountId, registry, groupId, artifactId, file, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadMavenPackageWithBody(ctx context.Context, accountId string, registry string, groupId string, artifactId string, version string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadMavenPackageRequestWithBody(c.Server, accountId, registry, groupId, artifactId, version, file, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadNPMPackageMetadata(ctx context.Context, accountId string, registry string, pPackage string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadNPMPackageMetadataRequest(c.Server, accountId, registry, pPackage)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadNPMPackageWithBody(ctx context.Context, accountId string, registry string, pPackage string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadNPMPackageRequestWithBody(c.Server, accountId, registry, pPackage, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadNugetPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadNugetPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadDartPackageWithBody(ctx context.Context, accountId string, registry string, uploadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadDartPackageRequestWithBody(c.Server, accountId, registry, uploadId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadPythonPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadPythonPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadRpmPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadRpmPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUploadCargoPackageRequestWithBody generates requests for UploadCargoPackage with any type of body
func NewUploadCargoPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/cargo/api/v1/crates/new", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadComposerPackageRequestWithBody generates requests for UploadComposerPackage with any type of body
func NewUploadComposerPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/composer/upload", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadCondaPackageRequestWithBody generates requests for UploadCondaPackage with any type of body
func NewUploadCondaPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/conda/upload", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteGenericFileFromPathRequest generates requests for DeleteGenericFileFromPath
func NewDeleteGenericFileFromPathRequest(server string, accountId string, registry string, filepath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDownloadGenericFileFromPathRequest generates requests for DownloadGenericFileFromPath
func NewDownloadGenericFileFromPathRequest(server string, accountId string, registry string, filepath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHeadGenericFileAtPathRequest generates requests for HeadGenericFileAtPath
func NewHeadGenericFileAtPathRequest(server string, accountId string, registry string, filepath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadGenericFileToPathRequestWithBody generates requests for UploadGenericFileToPath with any type of body
func NewUploadGenericFileToPathRequestWithBody(server string, accountId string, registry string, filepath string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDownloadGenericPackageRequest generates requests for DownloadGenericPackage
func NewDownloadGenericPackageRequest(server string, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/generic/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filename", runtime.ParamLocationQuery, params.Filename); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadGenericPackageRequestWithBody generates requests for UploadGenericPackage with any type of body
func NewUploadGenericPackageRequestWithBody(server string, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/generic/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadGoPackageRequestWithBody generates requests for UploadGoPackage with any type of body
func NewUploadGoPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/go/upload", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDownloadMavenMetadataXmlRequest generates requests for DownloadMavenMetadataXml
func NewDownloadMavenMetadataXmlRequest(server string, accountId string, registry string, groupId string, artifactId string, file string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "artifactId", runtime.ParamLocationPath, artifactId)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "file", runtime.ParamLocationPath, file)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/maven/%s/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadMavenMetadataXmlRequestWithBody generates requests for UploadMavenMetadataXml with any type of body
func NewUploadMavenMetadataXmlRequestWithBody(server string, accountId string, registry string, groupId string, artifactId string, file string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "artifactId", runtime.ParamLocationPath, artifactId)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "file", runtime.ParamLocationPath, file)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/maven/%s/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadMavenPackageRequestWithBody generates requests for UploadMavenPackage with any type of body
func NewUploadMavenPackageRequestWithBody(server string, accountId string, registry string, groupId string, artifactId string, version string, file string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "groupId", runtime.ParamLocationPath, groupId)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "artifactId", runtime.ParamLocationPath, artifactId)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	var pathParam5 string

	pathParam5, err = runtime.StyleParamWithLocation("simple", false, "file", runtime.ParamLocationPath, file)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/maven/%s/%s/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4, pathParam5)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDownloadNPMPackageMetadataRequest generates requests for DownloadNPMPackageMetadata
func NewDownloadNPMPackageMetadataRequest(server string, accountId string, registry string, pPackage string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/npm/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadNPMPackageRequestWithBody generates requests for UploadNPMPackage with any type of body
func NewUploadNPMPackageRequestWithBody(server string, accountId string, registry string, pPackage string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/npm/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadNugetPackageRequestWithBody generates requests for UploadNugetPackage with any type of body
func NewUploadNugetPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/nuget", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadDartPackageRequestWithBody generates requests for UploadDartPackage with any type of body
func NewUploadDartPackageRequestWithBody(server string, accountId string, registry string, uploadId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "uploadId", runtime.ParamLocationPath, uploadId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/pub/api/packages/versions/new/upload/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadPythonPackageRequestWithBody generates requests for UploadPythonPackage with any type of body
func NewUploadPythonPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/python", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadRpmPackageRequestWithBody generates requests for UploadRpmPackage with any type of body
func NewUploadRpmPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/rpm", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// UploadCargoPackageWithBodyWithResponse request with any body
	UploadCargoPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadCargoPackageResponse, error)

	// UploadComposerPackageWithBodyWithResponse request with any body
	UploadComposerPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadComposerPackageResponse, error)

	// UploadCondaPackageWithBodyWithResponse request with any body
	UploadCondaPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadCondaPackageResponse, error)

	// DeleteGenericFileFromPathWithResponse request
	DeleteGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*DeleteGenericFileFromPathResponse, error)

	// DownloadGenericFileFromPathWithResponse request
	DownloadGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*DownloadGenericFileFromPathResponse, error)

	// HeadGenericFileAtPathWithResponse request
	HeadGenericFileAtPathWithResponse(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*HeadGenericFileAtPathResponse, error)

	// UploadGenericFileToPathWithBodyWithResponse request with any body
	UploadGenericFileToPathWithBodyWithResponse(ctx context.Context, accountId string, registry string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericFileToPathResponse, error)

	// DownloadGenericPackageWithResponse request
	DownloadGenericPackageWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*DownloadGenericPackageResponse, error)

	// UploadGenericPackageWithBodyWithResponse request with any body
	UploadGenericPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericPackageResponse, error)

	// UploadGoPackageWithBodyWithResponse request with any body
	UploadGoPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGoPackageResponse, error)

	// DownloadMavenMetadataXmlWithResponse request
	DownloadMavenMetadataXmlWithResponse(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, reqEditors ...RequestEditorFn) (*DownloadMavenMetadataXmlResponse, error)

	// UploadMavenMetadataXmlWithBodyWithResponse request with any body
	UploadMavenMetadataXmlWithBodyWithResponse(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadMavenMetadataXmlResponse, error)

	// UploadMavenPackageWithBodyWithResponse request with any body
	UploadMavenPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, groupId string, artifactId string, version string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadMavenPackageResponse, error)

	// DownloadNPMPackageMetadataWithResponse request
	DownloadNPMPackageMetadataWithResponse(ctx context.Context, accountId string, registry string, pPackage string, reqEditors ...RequestEditorFn) (*DownloadNPMPackageMetadataResponse, error)

	// UploadNPMPackageWithBodyWithResponse request with any body
	UploadNPMPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadNPMPackageResponse, error)

	// UploadNugetPackageWithBodyWithResponse request with any body
	UploadNugetPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadNugetPackageResponse, error)

	// UploadDartPackageWithBodyWithResponse request with any body
	UploadDartPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, uploadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadDartPackageResponse, error)

	// UploadPythonPackageWithBodyWithResponse request with any body
	UploadPythonPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadPythonPackageResponse, error)

	// UploadRpmPackageWithBodyWithResponse request with any body
	UploadRpmPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadRpmPackageResponse, error)
}

type UploadCargoPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadCargoPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadCargoPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadComposerPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadComposerPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadComposerPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadCondaPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadCondaPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadCondaPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteGenericFileFromPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteGenericFileFromPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteGenericFileFromPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadGenericFileFromPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadGenericFileFromPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadGenericFileFromPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HeadGenericFileAtPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HeadGenericFileAtPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeadGenericFileAtPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadGenericFileToPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadGenericFileToPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadGenericFileToPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadGenericPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadGenericPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadGenericPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadGenericPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadGenericPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadGenericPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadGoPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadGoPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadGoPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadMavenMetadataXmlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadMavenMetadataXmlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadMavenMetadataXmlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadMavenMetadataXmlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadMavenMetadataXmlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadMavenMetadataXmlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadMavenPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadMavenPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadMavenPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadNPMPackageMetadataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadNPMPackageMetadataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadNPMPackageMetadataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadNPMPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadNPMPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadNPMPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadNugetPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadNugetPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadNugetPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadDartPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadDartPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadDartPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadPythonPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadPythonPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadPythonPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadRpmPackageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadRpmPackageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadRpmPackageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// UploadCargoPackageWithBodyWithResponse request with arbitrary body returning *UploadCargoPackageResponse
func (c *ClientWithResponses) UploadCargoPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadCargoPackageResponse, error) {
	rsp, err := c.UploadCargoPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadCargoPackageResponse(rsp)
}

// UploadComposerPackageWithBodyWithResponse request with arbitrary body returning *UploadComposerPackageResponse
func (c *ClientWithResponses) UploadComposerPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadComposerPackageResponse, error) {
	rsp, err := c.UploadComposerPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadComposerPackageResponse(rsp)
}

// UploadCondaPackageWithBodyWithResponse request with arbitrary body returning *UploadCondaPackageResponse
func (c *ClientWithResponses) UploadCondaPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadCondaPackageResponse, error) {
	rsp, err := c.UploadCondaPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadCondaPackageResponse(rsp)
}

// DeleteGenericFileFromPathWithResponse request returning *DeleteGenericFileFromPathResponse
func (c *ClientWithResponses) DeleteGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*DeleteGenericFileFromPathResponse, error) {
	rsp, err := c.DeleteGenericFileFromPath(ctx, accountId, registry, filepath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteGenericFileFromPathResponse(rsp)
}

// DownloadGenericFileFromPathWithResponse request returning *DownloadGenericFileFromPathResponse
func (c *ClientWithResponses) DownloadGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*DownloadGenericFileFromPathResponse, error) {
	rsp, err := c.DownloadGenericFileFromPath(ctx, accountId, registry, filepath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadGenericFileFromPathResponse(rsp)
}

// HeadGenericFileAtPathWithResponse request returning *HeadGenericFileAtPathResponse
func (c *ClientWithResponses) HeadGenericFileAtPathWithResponse(ctx context.Context, accountId string, registry string, filepath string, reqEditors ...RequestEditorFn) (*HeadGenericFileAtPathResponse, error) {
	rsp, err := c.HeadGenericFileAtPath(ctx, accountId, registry, filepath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeadGenericFileAtPathResponse(rsp)
}

// UploadGenericFileToPathWithBodyWithResponse request with arbitrary body returning *UploadGenericFileToPathResponse
func (c *ClientWithResponses) UploadGenericFileToPathWithBodyWithResponse(ctx context.Context, accountId string, registry string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericFileToPathResponse, error) {
	rsp, err := c.UploadGenericFileToPathWithBody(ctx, accountId, registry, filepath, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadGenericFileToPathResponse(rsp)
}

// DownloadGenericPackageWithResponse request returning *DownloadGenericPackageResponse
func (c *ClientWithResponses) DownloadGenericPackageWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*DownloadGenericPackageResponse, error) {
	rsp, err := c.DownloadGenericPackage(ctx, accountId, registry, pPackage, version, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadGenericPackageResponse(rsp)
}

// UploadGenericPackageWithBodyWithResponse request with arbitrary body returning *UploadGenericPackageResponse
func (c *ClientWithResponses) UploadGenericPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericPackageResponse, error) {
	rsp, err := c.UploadGenericPackageWithBody(ctx, accountId, registry, pPackage, version, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadGenericPackageResponse(rsp)
}

// UploadGoPackageWithBodyWithResponse request with arbitrary body returning *UploadGoPackageResponse
func (c *ClientWithResponses) UploadGoPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGoPackageResponse, error) {
	rsp, err := c.UploadGoPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadGoPackageResponse(rsp)
}

// DownloadMavenMetadataXmlWithResponse request returning *DownloadMavenMetadataXmlResponse
func (c *ClientWithResponses) DownloadMavenMetadataXmlWithResponse(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, reqEditors ...RequestEditorFn) (*DownloadMavenMetadataXmlResponse, error) {
	rsp, err := c.DownloadMavenMetadataXml(ctx, accountId, registry, groupId, artifactId, file, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadMavenMetadataXmlResponse(rsp)
}

// UploadMavenMetadataXmlWithBodyWithResponse request with arbitrary body returning *UploadMavenMetadataXmlResponse
func (c *ClientWithResponses) UploadMavenMetadataXmlWithBodyWithResponse(ctx context.Context, accountId string, registry string, groupId string, artifactId string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadMavenMetadataXmlResponse, error) {
	rsp, err := c.UploadMavenMetadataXmlWithBody(ctx, accountId, registry, groupId, artifactId, file, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadMavenMetadataXmlResponse(rsp)
}

// UploadMavenPackageWithBodyWithResponse request with arbitrary body returning *UploadMavenPackageResponse
func (c *ClientWithResponses) UploadMavenPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, groupId string, artifactId string, version string, file string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadMavenPackageResponse, error) {
	rsp, err := c.UploadMavenPackageWithBody(ctx, accountId, registry, groupId, artifactId, version, file, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadMavenPackageResponse(rsp)
}

// DownloadNPMPackageMetadataWithResponse request returning *DownloadNPMPackageMetadataResponse
func (c *ClientWithResponses) DownloadNPMPackageMetadataWithResponse(ctx context.Context, accountId string, registry string, pPackage string, reqEditors ...RequestEditorFn) (*DownloadNPMPackageMetadataResponse, error) {
	rsp, err := c.DownloadNPMPackageMetadata(ctx, accountId, registry, pPackage, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadNPMPackageMetadataResponse(rsp)
}

// UploadNPMPackageWithBodyWithResponse request with arbitrary body returning *UploadNPMPackageResponse
func (c *ClientWithResponses) UploadNPMPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadNPMPackageResponse, error) {
	rsp, err := c.UploadNPMPackageWithBody(ctx, accountId, registry, pPackage, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadNPMPackageResponse(rsp)
}

// UploadNugetPackageWithBodyWithResponse request with arbitrary body returning *UploadNugetPackageResponse
func (c *ClientWithResponses) UploadNugetPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadNugetPackageResponse, error) {
	rsp, err := c.UploadNugetPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadNugetPackageResponse(rsp)
}

// UploadDartPackageWithBodyWithResponse request with arbitrary body returning *UploadDartPackageResponse
func (c *ClientWithResponses) UploadDartPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, uploadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadDartPackageResponse, error) {
	rsp, err := c.UploadDartPackageWithBody(ctx, accountId, registry, uploadId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadDartPackageResponse(rsp)
}

// UploadPythonPackageWithBodyWithResponse request with arbitrary body returning *UploadPythonPackageResponse
func (c *ClientWithResponses) UploadPythonPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadPythonPackageResponse, error) {
	rsp, err := c.UploadPythonPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadPythonPackageResponse(rsp)
}

// UploadRpmPackageWithBodyWithResponse request with arbitrary body returning *UploadRpmPackageResponse
func (c *ClientWithResponses) UploadRpmPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadRpmPackageResponse, error) {
	rsp, err := c.UploadRpmPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadRpmPackageResponse(rsp)
}

// ParseUploadCargoPackageResponse parses an HTTP response from a UploadCargoPackageWithResponse call
func ParseUploadCargoPackageResponse(rsp *http.Response) (*UploadCargoPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadCargoPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadComposerPackageResponse parses an HTTP response from a UploadComposerPackageWithResponse call
func ParseUploadComposerPackageResponse(rsp *http.Response) (*UploadComposerPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadComposerPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadCondaPackageResponse parses an HTTP response from a UploadCondaPackageWithResponse call
func ParseUploadCondaPackageResponse(rsp *http.Response) (*UploadCondaPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadCondaPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteGenericFileFromPathResponse parses an HTTP response from a DeleteGenericFileFromPathWithResponse call
func ParseDeleteGenericFileFromPathResponse(rsp *http.Response) (*DeleteGenericFileFromPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteGenericFileFromPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDownloadGenericFileFromPathResponse parses an HTTP response from a DownloadGenericFileFromPathWithResponse call
func ParseDownloadGenericFileFromPathResponse(rsp *http.Response) (*DownloadGenericFileFromPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadGenericFileFromPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHeadGenericFileAtPathResponse parses an HTTP response from a HeadGenericFileAtPathWithResponse call
func ParseHeadGenericFileAtPathResponse(rsp *http.Response) (*HeadGenericFileAtPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeadGenericFileAtPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadGenericFileToPathResponse parses an HTTP response from a UploadGenericFileToPathWithResponse call
func ParseUploadGenericFileToPathResponse(rsp *http.Response) (*UploadGenericFileToPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadGenericFileToPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDownloadGenericPackageResponse parses an HTTP response from a DownloadGenericPackageWithResponse call
func ParseDownloadGenericPackageResponse(rsp *http.Response) (*DownloadGenericPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadGenericPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadGenericPackageResponse parses an HTTP response from a UploadGenericPackageWithResponse call
func ParseUploadGenericPackageResponse(rsp *http.Response) (*UploadGenericPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadGenericPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadGoPackageResponse parses an HTTP response from a UploadGoPackageWithResponse call
func ParseUploadGoPackageResponse(rsp *http.Response) (*UploadGoPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadGoPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDownloadMavenMetadataXmlResponse parses an HTTP response from a DownloadMavenMetadataXmlWithResponse call
func ParseDownloadMavenMetadataXmlResponse(rsp *http.Response) (*DownloadMavenMetadataXmlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadMavenMetadataXmlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadMavenMetadataXmlResponse parses an HTTP response from a UploadMavenMetadataXmlWithResponse call
func ParseUploadMavenMetadataXmlResponse(rsp *http.Response) (*UploadMavenMetadataXmlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadMavenMetadataXmlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadMavenPackageResponse parses an HTTP response from a UploadMavenPackageWithResponse call
func ParseUploadMavenPackageResponse(rsp *http.Response) (*UploadMavenPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadMavenPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDownloadNPMPackageMetadataResponse parses an HTTP response from a DownloadNPMPackageMetadataWithResponse call
func ParseDownloadNPMPackageMetadataResponse(rsp *http.Response) (*DownloadNPMPackageMetadataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadNPMPackageMetadataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadNPMPackageResponse parses an HTTP response from a UploadNPMPackageWithResponse call
func ParseUploadNPMPackageResponse(rsp *http.Response) (*UploadNPMPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadNPMPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadNugetPackageResponse parses an HTTP response from a UploadNugetPackageWithResponse call
func ParseUploadNugetPackageResponse(rsp *http.Response) (*UploadNugetPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadNugetPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadDartPackageResponse parses an HTTP response from a UploadDartPackageWithResponse call
func ParseUploadDartPackageResponse(rsp *http.Response) (*UploadDartPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadDartPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadPythonPackageResponse parses an HTTP response from a UploadPythonPackageWithResponse call
func ParseUploadPythonPackageResponse(rsp *http.Response) (*UploadPythonPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadPythonPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadRpmPackageResponse parses an HTTP response from a UploadRpmPackageWithResponse call
func ParseUploadRpmPackageResponse(rsp *http.Response) (*UploadRpmPackageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadRpmPackageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
