// Package ar_pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package ar_pkg

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// DownloadGenericPackageParams defines parameters for DownloadGenericPackage.
type DownloadGenericPackageParams struct {
	Filename string `form:"filename" json:"filename"`
}

// UploadGenericPackageMultipartBody defines parameters for UploadGenericPackage.
type UploadGenericPackageMultipartBody struct {
	// Description Human-readable description of the package/version
	Description *string `json:"description,omitempty"`

	// File Package file to upload
	File openapi_types.File `json:"file"`

	// Filename Original filename (mirrors form field `filename`)
	Filename string `json:"filename"`
}

// UploadGoPackageMultipartBody defines parameters for UploadGoPackage.
type UploadGoPackageMultipartBody struct {
	// Info Package .info file to upload
	Info openapi_types.File `json:"info"`

	// Mod Package .mod file to upload
	Mod openapi_types.File `json:"mod"`

	// Zip Package .zip file to upload
	Zip openapi_types.File `json:"zip"`
}

// UploadGenericPackageMultipartRequestBody defines body for UploadGenericPackage for multipart/form-data ContentType.
type UploadGenericPackageMultipartRequestBody UploadGenericPackageMultipartBody

// UploadGoPackageMultipartRequestBody defines body for UploadGoPackage for multipart/form-data ContentType.
type UploadGoPackageMultipartRequestBody UploadGoPackageMultipartBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// UploadComposerPackageWithBody request with any body
	UploadComposerPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadCondaPackageWithBody request with any body
	UploadCondaPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteGenericFileFromPath request
	DeleteGenericFileFromPath(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadGenericFileFromPath request
	DownloadGenericFileFromPath(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeadGenericFileAtPath request
	HeadGenericFileAtPath(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadGenericFileToPathWithBody request with any body
	UploadGenericFileToPathWithBody(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadGenericPackage request
	DownloadGenericPackage(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadGenericPackageWithBody request with any body
	UploadGenericPackageWithBody(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadGoPackageWithBody request with any body
	UploadGoPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) UploadComposerPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadComposerPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadCondaPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadCondaPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteGenericFileFromPath(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteGenericFileFromPathRequest(c.Server, accountId, registry, pPackage, version, filepath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadGenericFileFromPath(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadGenericFileFromPathRequest(c.Server, accountId, registry, pPackage, version, filepath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeadGenericFileAtPath(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeadGenericFileAtPathRequest(c.Server, accountId, registry, pPackage, version, filepath)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadGenericFileToPathWithBody(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadGenericFileToPathRequestWithBody(c.Server, accountId, registry, pPackage, version, filepath, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadGenericPackage(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadGenericPackageRequest(c.Server, accountId, registry, pPackage, version, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadGenericPackageWithBody(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadGenericPackageRequestWithBody(c.Server, accountId, registry, pPackage, version, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadGoPackageWithBody(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadGoPackageRequestWithBody(c.Server, accountId, registry, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUploadComposerPackageRequestWithBody generates requests for UploadComposerPackage with any type of body
func NewUploadComposerPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/composer/upload", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadCondaPackageRequestWithBody generates requests for UploadCondaPackage with any type of body
func NewUploadCondaPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/conda/upload", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteGenericFileFromPathRequest generates requests for DeleteGenericFileFromPath
func NewDeleteGenericFileFromPathRequest(server string, accountId string, registry string, pPackage string, version string, filepath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDownloadGenericFileFromPathRequest generates requests for DownloadGenericFileFromPath
func NewDownloadGenericFileFromPathRequest(server string, accountId string, registry string, pPackage string, version string, filepath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHeadGenericFileAtPathRequest generates requests for HeadGenericFileAtPath
func NewHeadGenericFileAtPathRequest(server string, accountId string, registry string, pPackage string, version string, filepath string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadGenericFileToPathRequestWithBody generates requests for UploadGenericFileToPath with any type of body
func NewUploadGenericFileToPathRequestWithBody(server string, accountId string, registry string, pPackage string, version string, filepath string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	var pathParam4 string

	pathParam4, err = runtime.StyleParamWithLocation("simple", false, "filepath", runtime.ParamLocationPath, filepath)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/files/%s/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3, pathParam4)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDownloadGenericPackageRequest generates requests for DownloadGenericPackage
func NewDownloadGenericPackageRequest(server string, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/generic/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filename", runtime.ParamLocationQuery, params.Filename); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUploadGenericPackageRequestWithBody generates requests for UploadGenericPackage with any type of body
func NewUploadGenericPackageRequestWithBody(server string, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "package", runtime.ParamLocationPath, pPackage)
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithLocation("simple", false, "version", runtime.ParamLocationPath, version)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/generic/%s/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUploadGoPackageRequestWithBody generates requests for UploadGoPackage with any type of body
func NewUploadGoPackageRequestWithBody(server string, accountId string, registry string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "accountId", runtime.ParamLocationPath, accountId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "registry", runtime.ParamLocationPath, registry)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pkg/%s/%s/go/upload", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// UploadComposerPackageWithBodyWithResponse request with any body
	UploadComposerPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadComposerPackageResp, error)

	// UploadCondaPackageWithBodyWithResponse request with any body
	UploadCondaPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadCondaPackageResp, error)

	// DeleteGenericFileFromPathWithResponse request
	DeleteGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*DeleteGenericFileFromPathResp, error)

	// DownloadGenericFileFromPathWithResponse request
	DownloadGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*DownloadGenericFileFromPathResp, error)

	// HeadGenericFileAtPathWithResponse request
	HeadGenericFileAtPathWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*HeadGenericFileAtPathResp, error)

	// UploadGenericFileToPathWithBodyWithResponse request with any body
	UploadGenericFileToPathWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericFileToPathResp, error)

	// DownloadGenericPackageWithResponse request
	DownloadGenericPackageWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*DownloadGenericPackageResp, error)

	// UploadGenericPackageWithBodyWithResponse request with any body
	UploadGenericPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericPackageResp, error)

	// UploadGoPackageWithBodyWithResponse request with any body
	UploadGoPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGoPackageResp, error)
}

type UploadComposerPackageResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadComposerPackageResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadComposerPackageResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadCondaPackageResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadCondaPackageResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadCondaPackageResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteGenericFileFromPathResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteGenericFileFromPathResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteGenericFileFromPathResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadGenericFileFromPathResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadGenericFileFromPathResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadGenericFileFromPathResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HeadGenericFileAtPathResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HeadGenericFileAtPathResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeadGenericFileAtPathResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadGenericFileToPathResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadGenericFileToPathResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadGenericFileToPathResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadGenericPackageResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadGenericPackageResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadGenericPackageResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadGenericPackageResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadGenericPackageResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadGenericPackageResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadGoPackageResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UploadGoPackageResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadGoPackageResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// UploadComposerPackageWithBodyWithResponse request with arbitrary body returning *UploadComposerPackageResp
func (c *ClientWithResponses) UploadComposerPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadComposerPackageResp, error) {
	rsp, err := c.UploadComposerPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadComposerPackageResp(rsp)
}

// UploadCondaPackageWithBodyWithResponse request with arbitrary body returning *UploadCondaPackageResp
func (c *ClientWithResponses) UploadCondaPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadCondaPackageResp, error) {
	rsp, err := c.UploadCondaPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadCondaPackageResp(rsp)
}

// DeleteGenericFileFromPathWithResponse request returning *DeleteGenericFileFromPathResp
func (c *ClientWithResponses) DeleteGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*DeleteGenericFileFromPathResp, error) {
	rsp, err := c.DeleteGenericFileFromPath(ctx, accountId, registry, pPackage, version, filepath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteGenericFileFromPathResp(rsp)
}

// DownloadGenericFileFromPathWithResponse request returning *DownloadGenericFileFromPathResp
func (c *ClientWithResponses) DownloadGenericFileFromPathWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*DownloadGenericFileFromPathResp, error) {
	rsp, err := c.DownloadGenericFileFromPath(ctx, accountId, registry, pPackage, version, filepath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadGenericFileFromPathResp(rsp)
}

// HeadGenericFileAtPathWithResponse request returning *HeadGenericFileAtPathResp
func (c *ClientWithResponses) HeadGenericFileAtPathWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, reqEditors ...RequestEditorFn) (*HeadGenericFileAtPathResp, error) {
	rsp, err := c.HeadGenericFileAtPath(ctx, accountId, registry, pPackage, version, filepath, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeadGenericFileAtPathResp(rsp)
}

// UploadGenericFileToPathWithBodyWithResponse request with arbitrary body returning *UploadGenericFileToPathResp
func (c *ClientWithResponses) UploadGenericFileToPathWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, filepath string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericFileToPathResp, error) {
	rsp, err := c.UploadGenericFileToPathWithBody(ctx, accountId, registry, pPackage, version, filepath, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadGenericFileToPathResp(rsp)
}

// DownloadGenericPackageWithResponse request returning *DownloadGenericPackageResp
func (c *ClientWithResponses) DownloadGenericPackageWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, params *DownloadGenericPackageParams, reqEditors ...RequestEditorFn) (*DownloadGenericPackageResp, error) {
	rsp, err := c.DownloadGenericPackage(ctx, accountId, registry, pPackage, version, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadGenericPackageResp(rsp)
}

// UploadGenericPackageWithBodyWithResponse request with arbitrary body returning *UploadGenericPackageResp
func (c *ClientWithResponses) UploadGenericPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, pPackage string, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGenericPackageResp, error) {
	rsp, err := c.UploadGenericPackageWithBody(ctx, accountId, registry, pPackage, version, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadGenericPackageResp(rsp)
}

// UploadGoPackageWithBodyWithResponse request with arbitrary body returning *UploadGoPackageResp
func (c *ClientWithResponses) UploadGoPackageWithBodyWithResponse(ctx context.Context, accountId string, registry string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadGoPackageResp, error) {
	rsp, err := c.UploadGoPackageWithBody(ctx, accountId, registry, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadGoPackageResp(rsp)
}

// ParseUploadComposerPackageResp parses an HTTP response from a UploadComposerPackageWithResponse call
func ParseUploadComposerPackageResp(rsp *http.Response) (*UploadComposerPackageResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadComposerPackageResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadCondaPackageResp parses an HTTP response from a UploadCondaPackageWithResponse call
func ParseUploadCondaPackageResp(rsp *http.Response) (*UploadCondaPackageResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadCondaPackageResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteGenericFileFromPathResp parses an HTTP response from a DeleteGenericFileFromPathWithResponse call
func ParseDeleteGenericFileFromPathResp(rsp *http.Response) (*DeleteGenericFileFromPathResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteGenericFileFromPathResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDownloadGenericFileFromPathResp parses an HTTP response from a DownloadGenericFileFromPathWithResponse call
func ParseDownloadGenericFileFromPathResp(rsp *http.Response) (*DownloadGenericFileFromPathResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadGenericFileFromPathResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHeadGenericFileAtPathResp parses an HTTP response from a HeadGenericFileAtPathWithResponse call
func ParseHeadGenericFileAtPathResp(rsp *http.Response) (*HeadGenericFileAtPathResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeadGenericFileAtPathResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadGenericFileToPathResp parses an HTTP response from a UploadGenericFileToPathWithResponse call
func ParseUploadGenericFileToPathResp(rsp *http.Response) (*UploadGenericFileToPathResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadGenericFileToPathResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDownloadGenericPackageResp parses an HTTP response from a DownloadGenericPackageWithResponse call
func ParseDownloadGenericPackageResp(rsp *http.Response) (*DownloadGenericPackageResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadGenericPackageResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadGenericPackageResp parses an HTTP response from a UploadGenericPackageWithResponse call
func ParseUploadGenericPackageResp(rsp *http.Response) (*UploadGenericPackageResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadGenericPackageResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUploadGoPackageResp parses an HTTP response from a UploadGoPackageWithResponse call
func ParseUploadGoPackageResp(rsp *http.Response) (*UploadGoPackageResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadGoPackageResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
