package nuget

import (
	"bytes"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/harness/harness-cli/cmd/pkgmgr"
	regcmd "github.com/harness/harness-cli/cmd/registry/command"
	"github.com/harness/harness-cli/config"
	p "github.com/harness/harness-cli/util/common/progress"

	"github.com/rs/zerolog/log"
)

var harURLPattern = regexp.MustCompile(`(?:https?://[^/]+)/(?:pkg/)?([^/]+)/([^/]+)/nuget/?`)

var has403Pattern = regexp.MustCompile(`(?i)(403\s*\(Forbidden\)|Response status code does not indicate success:\s*403|HTTP\s+403)`)

type NugetClient struct{}

func NewClient() *NugetClient {
	return &NugetClient{}
}

func (c *NugetClient) Name() string        { return pkgmgr.CommandDotnet }
func (c *NugetClient) PackageType() string { return pkgmgr.PackageTypeNuGet }

func (c *NugetClient) FallbackOrgProject() (string, string) {
	savedCfg, err := regcmd.LoadNugetRegistryConfig()
	if err != nil || savedCfg == nil {
		return "", ""
	}
	return savedCfg.OrgID, savedCfg.ProjectID
}

func (c *NugetClient) DetectFirewallError(stderr string) bool {
	return has403Pattern.MatchString(stderr)
}

func (c *NugetClient) DetectRegistry(explicitRegistry string) (*pkgmgr.RegistryInfo, error) {
	savedCfg, err := regcmd.LoadNugetRegistryConfig()
	if err == nil && savedCfg != nil && savedCfg.RegistryURL != "" {
		if explicitRegistry == "" || explicitRegistry == savedCfg.RegistryIdentifier {
			return &pkgmgr.RegistryInfo{
				RegistryURL:        savedCfg.RegistryURL,
				RegistryIdentifier: savedCfg.RegistryIdentifier,
				AccountID:          config.Global.AccountID,
				AuthToken:          config.Global.AuthToken,
			}, nil
		}
	}

	// Check NuGet.Config for HAR registry
	nugetConfPaths := getNugetConfigPaths()
	for _, path := range nugetConfPaths {
		info, err := parseNugetConfigForHAR(path, explicitRegistry)
		if err == nil && info != nil {
			return info, nil
		}
	}

	if explicitRegistry != "" {
		return nil, fmt.Errorf("HAR registry '%s' not found in NuGet configuration", explicitRegistry)
	}
	return nil, fmt.Errorf("no HAR registry found. Run 'hc registry configure nuget' first")
}

func (c *NugetClient) RunCommand(command string, args []string) (*pkgmgr.InstallResult, error) {
	cmdArgs := append([]string{command}, args...)
	cmd := exec.Command("dotnet", cmdArgs...)
	cmd.Dir = "."
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout

	var stderrBuf bytes.Buffer
	cmd.Stderr = io.MultiWriter(os.Stderr, &stderrBuf)

	log.Info().Strs("args", cmdArgs).Msgf("Running dotnet %s", command)

	err := cmd.Run()
	stderrStr := stderrBuf.String()

	if err != nil {
		return &pkgmgr.InstallResult{
			Status: "FAILURE",
			Stderr: stderrStr,
			Err:    err,
		}, nil
	}
	return &pkgmgr.InstallResult{
		Status: "SUCCESS",
		Stderr: stderrStr,
	}, nil
}

func (c *NugetClient) ResolveDependencies(progress p.Reporter) (*pkgmgr.DependencyResult, error) {
	noop := func() {}

	// Check for packages.lock.json first (generated by dotnet restore --use-lock-file)
	lockFiles := []string{"packages.lock.json"}
	// Also check project.assets.json in obj/
	if entries, err := filepath.Glob("**/obj/project.assets.json"); err == nil {
		lockFiles = append(lockFiles, entries...)
	}
	if _, err := os.Stat("obj/project.assets.json"); err == nil {
		lockFiles = append(lockFiles, "obj/project.assets.json")
	}

	for _, lockFile := range lockFiles {
		if _, err := os.Stat(lockFile); err == nil {
			progress.Step(fmt.Sprintf("Found %s, parsing dependencies", lockFile))
			if lockFile == "packages.lock.json" {
				deps, err := parsePackagesLockJson(lockFile)
				if err == nil && len(deps) > 0 {
					return &pkgmgr.DependencyResult{Dependencies: deps, Cleanup: noop}, nil
				}
			} else {
				deps, err := parseProjectAssetsJson(lockFile)
				if err == nil && len(deps) > 0 {
					return &pkgmgr.DependencyResult{Dependencies: deps, Cleanup: noop}, nil
				}
			}
		}
	}

	// Run dotnet list package --include-transitive --format json
	progress.Step("Running dotnet list package --include-transitive to resolve dependencies")
	cmd := exec.Command("dotnet", "list", "package", "--include-transitive", "--format", "json")
	cmd.Dir = "."
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		log.Warn().Err(err).Str("stderr", stderr.String()).Msg("dotnet list package failed")
		progress.Step("dotnet list package failed, falling back to csproj (direct deps only)")
		deps, parseErr := parseCsprojFiles()
		if parseErr != nil || len(deps) == 0 {
			return nil, fmt.Errorf("dotnet list package failed and no csproj deps found: %w", err)
		}
		return &pkgmgr.DependencyResult{Dependencies: deps, Cleanup: noop}, nil
	}

	deps, err := parseDotnetListOutput(stdout.String())
	if err != nil || len(deps) == 0 {
		progress.Step("Failed to parse dotnet list output, falling back to csproj")
		csprojDeps, _ := parseCsprojFiles()
		if len(csprojDeps) > 0 {
			return &pkgmgr.DependencyResult{Dependencies: csprojDeps, Cleanup: noop}, nil
		}
		return nil, fmt.Errorf("no dependencies resolved")
	}

	return &pkgmgr.DependencyResult{Dependencies: deps, Cleanup: noop}, nil
}

func parsePackagesLockJson(path string) ([]regcmd.Dependency, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var lockFile struct {
		Dependencies map[string]map[string]struct {
			Type     string `json:"type"`
			Resolved string `json:"resolved"`
		} `json:"dependencies"`
	}

	if err := json.Unmarshal(data, &lockFile); err != nil {
		return nil, fmt.Errorf("failed to parse packages.lock.json: %w", err)
	}

	deps := make([]regcmd.Dependency, 0)
	seen := make(map[string]bool)

	for _, framework := range lockFile.Dependencies {
		for name, info := range framework {
			key := name + "@" + info.Resolved
			if seen[key] {
				continue
			}
			seen[key] = true
			deps = append(deps, regcmd.Dependency{
				Name:    name,
				Version: info.Resolved,
				Source:  "packages.lock.json",
			})
		}
	}

	return deps, nil
}

func parseProjectAssetsJson(path string) ([]regcmd.Dependency, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var assets struct {
		Libraries map[string]struct {
			Type string `json:"type"`
		} `json:"libraries"`
	}

	if err := json.Unmarshal(data, &assets); err != nil {
		return nil, fmt.Errorf("failed to parse project.assets.json: %w", err)
	}

	deps := make([]regcmd.Dependency, 0)
	for lib, info := range assets.Libraries {
		if info.Type != "package" {
			continue
		}
		parts := strings.SplitN(lib, "/", 2)
		if len(parts) != 2 {
			continue
		}
		deps = append(deps, regcmd.Dependency{
			Name:    parts[0],
			Version: parts[1],
			Source:  "project.assets.json",
		})
	}

	return deps, nil
}

func parseDotnetListOutput(output string) ([]regcmd.Dependency, error) {
	// Try JSON format first
	var jsonOutput struct {
		Projects []struct {
			Frameworks []struct {
				TopLevelPackages  []struct{ ID, Version string } `json:"topLevelPackages"`
				TransitivePackages []struct{ ID, Version string } `json:"transitivePackages"`
			} `json:"frameworks"`
		} `json:"projects"`
	}

	if err := json.Unmarshal([]byte(output), &jsonOutput); err == nil {
		deps := make([]regcmd.Dependency, 0)
		seen := make(map[string]bool)
		for _, proj := range jsonOutput.Projects {
			for _, fw := range proj.Frameworks {
				for _, pkg := range fw.TopLevelPackages {
					key := pkg.ID + "@" + pkg.Version
					if !seen[key] {
						seen[key] = true
						deps = append(deps, regcmd.Dependency{Name: pkg.ID, Version: pkg.Version, Source: "dotnet-list"})
					}
				}
				for _, pkg := range fw.TransitivePackages {
					key := pkg.ID + "@" + pkg.Version
					if !seen[key] {
						seen[key] = true
						deps = append(deps, regcmd.Dependency{Name: pkg.ID, Version: pkg.Version, Source: "dotnet-list"})
					}
				}
			}
		}
		return deps, nil
	}

	// Fallback: parse text output
	deps := make([]regcmd.Dependency, 0)
	seen := make(map[string]bool)
	depPattern := regexp.MustCompile(`>\s+(\S+)\s+(\S+)\s+(\S+)`)

	for _, line := range strings.Split(output, "\n") {
		matches := depPattern.FindStringSubmatch(line)
		if len(matches) < 4 {
			continue
		}
		name := matches[1]
		version := matches[3] // resolved version
		key := name + "@" + version
		if !seen[key] {
			seen[key] = true
			deps = append(deps, regcmd.Dependency{Name: name, Version: version, Source: "dotnet-list"})
		}
	}

	return deps, nil
}

func parseCsprojFiles() ([]regcmd.Dependency, error) {
	csprojFiles, err := filepath.Glob("*.csproj")
	if err != nil || len(csprojFiles) == 0 {
		csprojFiles = findCsprojRecursive()
	}
	if len(csprojFiles) == 0 {
		return nil, fmt.Errorf("no .csproj files found")
	}

	deps := make([]regcmd.Dependency, 0)
	seen := make(map[string]bool)

	for _, csproj := range csprojFiles {
		data, err := os.ReadFile(csproj)
		if err != nil {
			continue
		}

		type PackageRef struct {
			Include string `xml:"Include,attr"`
			Version string `xml:"Version,attr"`
		}
		type ItemGroup struct {
			PackageReferences []PackageRef `xml:"PackageReference"`
		}
		type Project struct {
			ItemGroups []ItemGroup `xml:"ItemGroup"`
		}

		var proj Project
		if err := xml.Unmarshal(data, &proj); err != nil {
			continue
		}

		for _, ig := range proj.ItemGroups {
			for _, ref := range ig.PackageReferences {
				if ref.Include == "" {
					continue
				}
				key := ref.Include + "@" + ref.Version
				if seen[key] {
					continue
				}
				seen[key] = true
				version := ref.Version
				if version == "" {
					version = "latest"
				}
				deps = append(deps, regcmd.Dependency{
					Name:    ref.Include,
					Version: version,
					Source:  filepath.Base(csproj),
				})
			}
		}
	}

	return deps, nil
}

func getNugetConfigPaths() []string {
	paths := []string{"nuget.config", "NuGet.Config", "NuGet.config"}
	if homeDir, err := os.UserHomeDir(); err == nil {
		paths = append(paths, filepath.Join(homeDir, ".nuget", "NuGet", "NuGet.Config"))
	}
	return paths
}

func parseNugetConfigForHAR(confPath, explicitRegistry string) (*pkgmgr.RegistryInfo, error) {
	data, err := os.ReadFile(confPath)
	if err != nil {
		return nil, err
	}

	type PackageSource struct {
		Key   string `xml:"key,attr"`
		Value string `xml:"value,attr"`
	}
	type PackageSourceCredential struct {
		XMLName  xml.Name `xml:""`
		Username struct {
			Value string `xml:"value,attr"`
		} `xml:"add"`
	}
	type Configuration struct {
		XMLName        xml.Name `xml:"configuration"`
		PackageSources struct {
			Sources []PackageSource `xml:"add"`
		} `xml:"packageSources"`
	}

	var conf Configuration
	if err := xml.Unmarshal(data, &conf); err != nil {
		return nil, err
	}

	for _, source := range conf.PackageSources.Sources {
		if !harURLPattern.MatchString(source.Value) {
			continue
		}
		matches := harURLPattern.FindStringSubmatch(source.Value)
		if len(matches) < 3 {
			continue
		}
		registryIdentifier := matches[2]
		if explicitRegistry != "" && registryIdentifier != explicitRegistry {
			continue
		}
		return &pkgmgr.RegistryInfo{
			RegistryURL:        source.Value,
			AccountID:          matches[1],
			RegistryIdentifier: registryIdentifier,
			AuthToken:          config.Global.AuthToken,
		}, nil
	}

	return nil, fmt.Errorf("no HAR registry URL found in %s", confPath)
}

func findCsprojRecursive() []string {
	var files []string
	_ = filepath.WalkDir(".", func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if !d.IsDir() && strings.HasSuffix(path, ".csproj") {
			files = append(files, path)
		}
		return nil
	})
	return files
}
