package nuget

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"regexp"
	"strings"

	"github.com/harness/harness-cli/cmd/pkgmgr"
	regcmd "github.com/harness/harness-cli/cmd/registry/command"
	p "github.com/harness/harness-cli/util/common/progress"

	"github.com/rs/zerolog/log"
)

// has403Pattern detects 403 Forbidden in dotnet restore output.
// dotnet outputs: "Response status code does not indicate success: 403 (Forbidden)."
var has403Pattern = regexp.MustCompile(`(?i)403|[Ff]orbidden`)

// NuGetClient implements pkgmgr.Client for NuGet/dotnet.
type NuGetClient struct{}

func NewClient() *NuGetClient {
	return &NuGetClient{}
}

func (c *NuGetClient) Name() string        { return "dotnet" }
func (c *NuGetClient) PackageType() string { return "nuget" }

func (c *NuGetClient) DetectFirewallError(stderr string) bool {
	return has403Pattern.MatchString(stderr)
}

func (c *NuGetClient) FallbackOrgProject() (string, string) {
	cfg, err := regcmd.LoadNuGetRegistryConfig()
	if err != nil {
		return "", ""
	}
	return cfg.OrgID, cfg.ProjectID
}

// DetectRegistry detects the HAR registry from saved nuget config or explicit flag.
func (c *NuGetClient) DetectRegistry(explicitRegistry string) (*pkgmgr.RegistryInfo, error) {
	if explicitRegistry != "" {
		return &pkgmgr.RegistryInfo{
			RegistryIdentifier: explicitRegistry,
		}, nil
	}

	cfg, err := regcmd.LoadNuGetRegistryConfig()
	if err == nil && cfg.RegistryIdentifier != "" {
		log.Info().Str("registry", cfg.RegistryIdentifier).Msg("Using saved nuget registry config")
		return &pkgmgr.RegistryInfo{
			RegistryIdentifier: cfg.RegistryIdentifier,
		}, nil
	}

	return nil, fmt.Errorf("no registry configured. Run 'hc registry configure nuget --registry <name>' first, or use --registry flag")
}

// RunCommand executes a native dotnet command with live output streaming.
// If a project-level nuget.config exists and no --configfile flag is provided, it adds --configfile nuget.config.
func (c *NuGetClient) RunCommand(command string, args []string) (*pkgmgr.InstallResult, error) {
	dotnetPath, err := exec.LookPath("dotnet")
	if err != nil {
		return nil, fmt.Errorf("dotnet not found in PATH: %w", err)
	}

	cmdArgs := append([]string{command}, args...)

	// Auto-inject project-level nuget.config if it exists and user didn't specify --configfile
	if !containsConfigFlag(args) {
		if _, err := os.Stat("nuget.config"); err == nil {
			log.Info().Msg("Using project-level nuget.config")
			cmdArgs = append(cmdArgs, "--configfile", "nuget.config")
		}
	}

	cmd := exec.Command(dotnetPath, cmdArgs...)
	cmd.Dir = "."
	cmd.Stdin = os.Stdin

	// dotnet writes errors to both stdout and stderr
	var stdoutBuf, stderrBuf bytes.Buffer
	cmd.Stdout = io.MultiWriter(os.Stdout, &stdoutBuf)
	cmd.Stderr = io.MultiWriter(os.Stderr, &stderrBuf)

	log.Info().Strs("args", cmdArgs).Msgf("Running dotnet %s", command)

	err = cmd.Run()
	combinedOutput := stdoutBuf.String() + "\n" + stderrBuf.String()

	if err != nil {
		return &pkgmgr.InstallResult{Status: "FAILURE", Stderr: combinedOutput, Err: err}, nil
	}
	return &pkgmgr.InstallResult{Status: "SUCCESS", Stderr: combinedOutput}, nil
}

// ResolveDependencies resolves NuGet dependencies.
// Primary: parse project.assets.json (generated by dotnet restore).
// Secondary: run `dotnet list package --include-transitive --format json`.
// Fallback: parse .csproj for direct PackageReference entries.
func (c *NuGetClient) ResolveDependencies(progress p.Reporter) (*pkgmgr.DependencyResult, error) {
	noop := func() {}

	// Try dotnet list package --include-transitive --format json
	deps, err := runDotnetListPackages()
	if err == nil && len(deps) > 0 {
		progress.Step(fmt.Sprintf("Resolved %d dependencies via dotnet list package", len(deps)))
		return &pkgmgr.DependencyResult{Dependencies: deps, Cleanup: noop}, nil
	}
	log.Warn().Err(err).Msg("dotnet list package failed, falling back to .csproj parsing")

	// Fallback: parse .csproj files for PackageReference
	deps, err = parseCsprojFiles()
	if err == nil && len(deps) > 0 {
		progress.Step(fmt.Sprintf("Parsed %d direct dependencies from .csproj", len(deps)))
		return &pkgmgr.DependencyResult{Dependencies: deps, Cleanup: noop}, nil
	}

	return nil, fmt.Errorf("no NuGet dependencies found. Ensure a .csproj or .sln file exists")
}

// dotnetListPackageOutput represents the JSON output of `dotnet list package --format json`.
type dotnetListPackageOutput struct {
	Projects []struct {
		Frameworks []struct {
			TopLevelPackages   []dotnetPackageRef `json:"topLevelPackages"`
			TransitivePackages []dotnetPackageRef `json:"transitivePackages"`
		} `json:"frameworks"`
	} `json:"projects"`
}

type dotnetPackageRef struct {
	ID               string `json:"id"`
	ResolvedVersion  string `json:"resolvedVersion"`
	RequestedVersion string `json:"requestedVersion,omitempty"`
}

// runDotnetListPackages runs `dotnet list package --include-transitive --format json` and parses the output.
func runDotnetListPackages() ([]regcmd.Dependency, error) {
	dotnetPath, err := exec.LookPath("dotnet")
	if err != nil {
		return nil, fmt.Errorf("dotnet not found: %w", err)
	}

	cmdArgs := []string{"list", "package", "--include-transitive", "--format", "json"}

	// Use project-level nuget.config if it exists
	if _, err := os.Stat("nuget.config"); err == nil {
		cmdArgs = append(cmdArgs, "--configfile", "nuget.config")
	}

	cmd := exec.Command(dotnetPath, cmdArgs...)
	cmd.Dir = "."

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	log.Info().Strs("args", cmdArgs).Msg("Running dotnet list package")

	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("dotnet list package failed: %w (stderr: %s)", err, stderr.String())
	}

	var output dotnetListPackageOutput
	if err := json.Unmarshal(stdout.Bytes(), &output); err != nil {
		return nil, fmt.Errorf("failed to parse dotnet list package output: %w", err)
	}

	var deps []regcmd.Dependency
	seen := make(map[string]bool)

	for _, project := range output.Projects {
		for _, framework := range project.Frameworks {
			for _, pkg := range framework.TopLevelPackages {
				key := pkg.ID + "@" + pkg.ResolvedVersion
				if seen[key] {
					continue
				}
				seen[key] = true
				deps = append(deps, regcmd.Dependency{
					Name:    pkg.ID,
					Version: pkg.ResolvedVersion,
					Source:  "dotnet-list-package",
				})
			}
			for _, pkg := range framework.TransitivePackages {
				key := pkg.ID + "@" + pkg.ResolvedVersion
				if seen[key] {
					continue
				}
				seen[key] = true
				deps = append(deps, regcmd.Dependency{
					Name:    pkg.ID,
					Version: pkg.ResolvedVersion,
					Source:  "dotnet-list-package-transitive",
				})
			}
		}
	}

	return deps, nil
}

// parseCsprojFiles parses all .csproj files in the current directory for PackageReference entries.
func parseCsprojFiles() ([]regcmd.Dependency, error) {
	entries, err := os.ReadDir(".")
	if err != nil {
		return nil, err
	}

	var deps []regcmd.Dependency
	seen := make(map[string]bool)
	pkgRefPattern := regexp.MustCompile(`<PackageReference\s+Include="([^"]+)"\s+Version="([^"]+)"`)

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".csproj") {
			continue
		}

		data, err := os.ReadFile(entry.Name())
		if err != nil {
			continue
		}

		matches := pkgRefPattern.FindAllStringSubmatch(string(data), -1)
		for _, match := range matches {
			name := match[1]
			version := match[2]
			if seen[name] {
				continue
			}
			seen[name] = true
			deps = append(deps, regcmd.Dependency{
				Name:    name,
				Version: version,
				Source:  "csproj",
			})
		}
	}

	if len(deps) == 0 {
		return nil, fmt.Errorf("no PackageReference found in .csproj files")
	}
	return deps, nil
}

// containsConfigFlag checks if args already contain --configfile.
func containsConfigFlag(args []string) bool {
	for _, a := range args {
		if a == "--configfile" || strings.HasPrefix(a, "--configfile=") {
			return true
		}
	}
	return false
}
