// Package ar_v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package ar_v2

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for MetadataType.
const (
	AUTO   MetadataType = "AUTO"
	MANUAL MetadataType = "MANUAL"
)

// Defines values for Status.
const (
	ERROR   Status = "ERROR"
	FAILURE Status = "FAILURE"
	SUCCESS Status = "SUCCESS"
)

// Error Standard error response with code, message and optional details
type Error struct {
	// Code The HTTP error code
	Code string `json:"code"`

	// Details Additional context and details about the error.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message explaining what went wrong
	Message string `json:"message"`
}

// MetadataInput Request payload containing metadata items to add or update for a specific entity.
type MetadataInput struct {
	// Metadata Array of metadata key-value pairs
	Metadata []MetadataItemInput `json:"metadata"`

	// Package Optional package name.
	Package *string `json:"package,omitempty"`

	// RegistryIdentifier The unique identifier of the registry where the metadata will be applied.
	RegistryIdentifier string `json:"registryIdentifier"`

	// Version Optional version identifier.
	Version *string `json:"version,omitempty"`
}

// MetadataItemInput Metadata key-value pair for create/update operations
type MetadataItemInput struct {
	// Key The metadata key name (case-sensitive)
	Key string `json:"key"`

	// Value The metadata value
	Value string `json:"value"`
}

// MetadataItemOutput Metadata entry
type MetadataItemOutput struct {
	// Id Unique identifier for this metadata entry
	Id string `json:"id"`

	// Key The metadata key name
	Key string `json:"key"`

	// Type Indicates if metadata was manually added (MANUAL) or system-generated (AUTO)
	Type MetadataType `json:"type"`

	// Value The metadata value
	Value string `json:"value"`
}

// MetadataOutput Response containing all metadata entries for an entity
type MetadataOutput struct {
	// Metadata Array of metadata entries
	Metadata []MetadataItemOutput `json:"metadata"`
}

// MetadataType Indicates if metadata was manually added (MANUAL) or system-generated (AUTO)
type MetadataType string

// Status Request processing status indicator
type Status string

// AccountIdentifier defines model for AccountIdentifier.
type AccountIdentifier = string

// ArtifactType defines model for ArtifactType.
type ArtifactType = string

// PackageParam defines model for PackageParam.
type PackageParam = string

// RegistryIdentifier defines model for RegistryIdentifier.
type RegistryIdentifier = string

// SrcArtifact defines model for SrcArtifact.
type SrcArtifact = string

// SrcRegistryIdentifier defines model for SrcRegistryIdentifier.
type SrcRegistryIdentifier = string

// SrcVersion defines model for SrcVersion.
type SrcVersion = string

// TargetRegistryIdentifier defines model for TargetRegistryIdentifier.
type TargetRegistryIdentifier = string

// VersionParam defines model for VersionParam.
type VersionParam = string

// BadRequest Standard error response with code, message and optional details
type BadRequest = Error

// InternalServerError Standard error response with code, message and optional details
type InternalServerError = Error

// MetadataResponse defines model for MetadataResponse.
type MetadataResponse struct {
	// Data Response containing all metadata entries for an entity
	Data MetadataOutput `json:"data"`

	// Status Request processing status indicator
	Status Status `json:"status"`
}

// NotFound Standard error response with code, message and optional details
type NotFound = Error

// Success defines model for Success.
type Success struct {
	// Status Request processing status indicator
	Status Status `json:"status"`
}

// Unauthenticated Standard error response with code, message and optional details
type Unauthenticated = Error

// Unauthorized Standard error response with code, message and optional details
type Unauthorized = Error

// MetadataRequest Request payload containing metadata items to add or update for a specific entity.
type MetadataRequest = MetadataInput

// CopyRegistryPackageParams defines parameters for CopyRegistryPackage.
type CopyRegistryPackageParams struct {
	// AccountIdentifier Unique identifier for the Harness account.
	AccountIdentifier AccountIdentifier `form:"account_identifier" json:"account_identifier"`

	// SrcRegistryIdentifier Source registry from where to copy
	SrcRegistryIdentifier SrcRegistryIdentifier `form:"src_registry_identifier" json:"src_registry_identifier"`

	// TargetRegistryIdentifier target registry where package will be copied
	TargetRegistryIdentifier TargetRegistryIdentifier `form:"target_registry_identifier" json:"target_registry_identifier"`

	// SrcArtifact artifact name to be copied
	SrcArtifact SrcArtifact `form:"src_artifact" json:"src_artifact"`

	// SrcVersion version to be copied
	SrcVersion SrcVersion `form:"src_version" json:"src_version"`

	// ArtifactType Name of the artifact type e.g model and datasets used for hugging face
	ArtifactType *ArtifactType `form:"artifact_type,omitempty" json:"artifact_type,omitempty"`
}

// DeleteMetadataParams defines parameters for DeleteMetadata.
type DeleteMetadataParams struct {
	// AccountIdentifier Unique identifier for the Harness account.
	AccountIdentifier AccountIdentifier `form:"account_identifier" json:"account_identifier"`
}

// GetMetadataParams defines parameters for GetMetadata.
type GetMetadataParams struct {
	// AccountIdentifier Unique identifier for the Harness account.
	AccountIdentifier AccountIdentifier `form:"account_identifier" json:"account_identifier"`

	// RegistryIdentifier Unique identifier for the artifact registry.
	RegistryIdentifier RegistryIdentifier `form:"registry_identifier" json:"registry_identifier"`

	// Package Name of the package
	Package *PackageParam `form:"package,omitempty" json:"package,omitempty"`

	// Version Name of the package version
	Version *VersionParam `form:"version,omitempty" json:"version,omitempty"`
}

// UpdateMetadataParams defines parameters for UpdateMetadata.
type UpdateMetadataParams struct {
	// AccountIdentifier Unique identifier for the Harness account.
	AccountIdentifier AccountIdentifier `form:"account_identifier" json:"account_identifier"`
}

// DeleteMetadataJSONRequestBody defines body for DeleteMetadata for application/json ContentType.
type DeleteMetadataJSONRequestBody = MetadataInput

// UpdateMetadataJSONRequestBody defines body for UpdateMetadata for application/json ContentType.
type UpdateMetadataJSONRequestBody = MetadataInput

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CopyRegistryPackage request
	CopyRegistryPackage(ctx context.Context, params *CopyRegistryPackageParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteMetadataWithBody request with any body
	DeleteMetadataWithBody(ctx context.Context, params *DeleteMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteMetadata(ctx context.Context, params *DeleteMetadataParams, body DeleteMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMetadata request
	GetMetadata(ctx context.Context, params *GetMetadataParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateMetadataWithBody request with any body
	UpdateMetadataWithBody(ctx context.Context, params *UpdateMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateMetadata(ctx context.Context, params *UpdateMetadataParams, body UpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CopyRegistryPackage(ctx context.Context, params *CopyRegistryPackageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCopyRegistryPackageRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteMetadataWithBody(ctx context.Context, params *DeleteMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMetadataRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteMetadata(ctx context.Context, params *DeleteMetadataParams, body DeleteMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMetadataRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMetadata(ctx context.Context, params *GetMetadataParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMetadataRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMetadataWithBody(ctx context.Context, params *UpdateMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateMetadataRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMetadata(ctx context.Context, params *UpdateMetadataParams, body UpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateMetadataRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCopyRegistryPackageRequest generates requests for CopyRegistryPackage
func NewCopyRegistryPackageRequest(server string, params *CopyRegistryPackageParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/copy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "account_identifier", runtime.ParamLocationQuery, params.AccountIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "src_registry_identifier", runtime.ParamLocationQuery, params.SrcRegistryIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "target_registry_identifier", runtime.ParamLocationQuery, params.TargetRegistryIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "src_artifact", runtime.ParamLocationQuery, params.SrcArtifact); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "src_version", runtime.ParamLocationQuery, params.SrcVersion); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.ArtifactType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "artifact_type", runtime.ParamLocationQuery, *params.ArtifactType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteMetadataRequest calls the generic DeleteMetadata builder with application/json body
func NewDeleteMetadataRequest(server string, params *DeleteMetadataParams, body DeleteMetadataJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteMetadataRequestWithBody(server, params, "application/json", bodyReader)
}

// NewDeleteMetadataRequestWithBody generates requests for DeleteMetadata with any type of body
func NewDeleteMetadataRequestWithBody(server string, params *DeleteMetadataParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "account_identifier", runtime.ParamLocationQuery, params.AccountIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetMetadataRequest generates requests for GetMetadata
func NewGetMetadataRequest(server string, params *GetMetadataParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "account_identifier", runtime.ParamLocationQuery, params.AccountIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "registry_identifier", runtime.ParamLocationQuery, params.RegistryIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Package != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "package", runtime.ParamLocationQuery, *params.Package); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, *params.Version); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateMetadataRequest calls the generic UpdateMetadata builder with application/json body
func NewUpdateMetadataRequest(server string, params *UpdateMetadataParams, body UpdateMetadataJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateMetadataRequestWithBody(server, params, "application/json", bodyReader)
}

// NewUpdateMetadataRequestWithBody generates requests for UpdateMetadata with any type of body
func NewUpdateMetadataRequestWithBody(server string, params *UpdateMetadataParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "account_identifier", runtime.ParamLocationQuery, params.AccountIdentifier); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CopyRegistryPackageWithResponse request
	CopyRegistryPackageWithResponse(ctx context.Context, params *CopyRegistryPackageParams, reqEditors ...RequestEditorFn) (*CopyRegistryPackageResp, error)

	// DeleteMetadataWithBodyWithResponse request with any body
	DeleteMetadataWithBodyWithResponse(ctx context.Context, params *DeleteMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteMetadataResp, error)

	DeleteMetadataWithResponse(ctx context.Context, params *DeleteMetadataParams, body DeleteMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteMetadataResp, error)

	// GetMetadataWithResponse request
	GetMetadataWithResponse(ctx context.Context, params *GetMetadataParams, reqEditors ...RequestEditorFn) (*GetMetadataResp, error)

	// UpdateMetadataWithBodyWithResponse request with any body
	UpdateMetadataWithBodyWithResponse(ctx context.Context, params *UpdateMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMetadataResp, error)

	UpdateMetadataWithResponse(ctx context.Context, params *UpdateMetadataParams, body UpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMetadataResp, error)
}

type CopyRegistryPackageResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Success
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r CopyRegistryPackageResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CopyRegistryPackageResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteMetadataResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Success
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r DeleteMetadataResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteMetadataResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMetadataResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetadataResponse
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetMetadataResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMetadataResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateMetadataResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetadataResponse
	JSON400      *BadRequest
	JSON401      *Unauthenticated
	JSON403      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r UpdateMetadataResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateMetadataResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CopyRegistryPackageWithResponse request returning *CopyRegistryPackageResp
func (c *ClientWithResponses) CopyRegistryPackageWithResponse(ctx context.Context, params *CopyRegistryPackageParams, reqEditors ...RequestEditorFn) (*CopyRegistryPackageResp, error) {
	rsp, err := c.CopyRegistryPackage(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCopyRegistryPackageResp(rsp)
}

// DeleteMetadataWithBodyWithResponse request with arbitrary body returning *DeleteMetadataResp
func (c *ClientWithResponses) DeleteMetadataWithBodyWithResponse(ctx context.Context, params *DeleteMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteMetadataResp, error) {
	rsp, err := c.DeleteMetadataWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMetadataResp(rsp)
}

func (c *ClientWithResponses) DeleteMetadataWithResponse(ctx context.Context, params *DeleteMetadataParams, body DeleteMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteMetadataResp, error) {
	rsp, err := c.DeleteMetadata(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMetadataResp(rsp)
}

// GetMetadataWithResponse request returning *GetMetadataResp
func (c *ClientWithResponses) GetMetadataWithResponse(ctx context.Context, params *GetMetadataParams, reqEditors ...RequestEditorFn) (*GetMetadataResp, error) {
	rsp, err := c.GetMetadata(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMetadataResp(rsp)
}

// UpdateMetadataWithBodyWithResponse request with arbitrary body returning *UpdateMetadataResp
func (c *ClientWithResponses) UpdateMetadataWithBodyWithResponse(ctx context.Context, params *UpdateMetadataParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMetadataResp, error) {
	rsp, err := c.UpdateMetadataWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMetadataResp(rsp)
}

func (c *ClientWithResponses) UpdateMetadataWithResponse(ctx context.Context, params *UpdateMetadataParams, body UpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMetadataResp, error) {
	rsp, err := c.UpdateMetadata(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMetadataResp(rsp)
}

// ParseCopyRegistryPackageResp parses an HTTP response from a CopyRegistryPackageWithResponse call
func ParseCopyRegistryPackageResp(rsp *http.Response) (*CopyRegistryPackageResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CopyRegistryPackageResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Success
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteMetadataResp parses an HTTP response from a DeleteMetadataWithResponse call
func ParseDeleteMetadataResp(rsp *http.Response) (*DeleteMetadataResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteMetadataResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Success
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetMetadataResp parses an HTTP response from a GetMetadataWithResponse call
func ParseGetMetadataResp(rsp *http.Response) (*GetMetadataResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMetadataResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateMetadataResp parses an HTTP response from a UpdateMetadataWithResponse call
func ParseUpdateMetadataResp(rsp *http.Response) (*UpdateMetadataResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateMetadataResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthenticated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
